### ISSUE TITLE
[Request] Port open file fixes to single-file version

### ISSUE THREAD

**Issue by dakcarto** [dtarb/TauDEM#1]
Hi. On Mac OS X, I am seeing many processes of the single-file version (5.1.1) of TauDEM finishing with open file handles, whereby the output file(s) become unreadable by other apps. It looks like this has been fixed in 45686615, and maybe other commits in this repository.

I would like to know if these fixes are planned to be ported to the single-file version? Thanks.

**Comment by dtarb** [comment]
@snorfalorpagus sorry it took me so long to get to this.  I finally got to look at this.  Your files appear to be pre-pended with some Mac metadata.  When I look at your file in hex I get 
![c1](https://cloud.githubusercontent.com/assets/3456833/5594377/367d4164-9206-11e4-9491-b5262b1a38f9.JPG)

This is header information giving the file name and your username.

Looking further down I see the signature of the start of a tiff file 49492A00
![c2](https://cloud.githubusercontent.com/assets/3456833/5594390/8d7ebcf4-9206-11e4-8e83-ee472535cef3.JPG)

I am able to edit the content before 49492A00 out of the file then read it in ArcMap and use it as an input to TauDEM which then works.

**Comment by dtarb** [comment]
The questions above appear to be answered.  The GDAL implementation changes the file writing strategy to be the following

(rank indicates processor number)
If rank ==0  create and initialize raster file
  write partition
  close raster
  send message to rank 1
if rank > 0
  wait till message received from rank - 1
  open raster
  write partition
  flush and  close raster
  if rank < size - 1  send message to rank+1 

This effectively performs writing in series with only one process having the raster open at a time and should resolve these issues.  So I am closing this issue.
