### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Verafeng** [dtarb/TauDEM#106]
I have a problem with TauDEM installation.
I am trying to use TauDEM for a hydro lab(MFD algorithms) ,but  I couldn't downlaod the TauDEM 5.3.7 Complete Windows installer successfully ,although I had try many times.
Can you give me a little bit of support with this issue? or send the installation package to my mail box.
15299193518@163.com

thank you!

**Comment by dtarb** [comment]
What is not working with the download?  You can also get the file directly from https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_prerelease_setup.exe which is the link to the latest release in this repo.

**Comment by Verafeng** [comment]
Thank you! The installation problem has been solved. And I have another question to consult with you . The taudem tools has the function of calculating the D-infinity flow directions,but I didn't find the function of flow accumulation . Does it have this feature?


发自网易邮箱大师
On 11/23/2016 20:16, David Tarboton wrote:

What is not working with the download? You can also get the file directly from https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_prerelease_setup.exe which is the link to the latest release in this repo.

**Comment by dtarb** [comment]
The function "D-infinity contributing area" of Areadinf is the D-infinity equivalent of flow accumulation.  See http://hydrology.usu.edu/taudem/taudem5/help53/DInfinityContributingArea.html.

**Comment by Marziye368** [comment]
Below page not found!
https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_prerelease_setup.exe
What can I do?

**Comment by dtarb** [comment]
Use https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_setup.exe linked in https://github.com/dtarb/TauDEM/releases/tag/v5.3.7
