### ISSUE TITLE
Error 000732 while calculating avalanche runout

### ISSUE THREAD

**Issue by ThreeTone** [dtarb/TauDEM#112]
Hello dtarb,
we get an error message while calculating the avalanche runout  (TauDEM 5.3.7 with ArcGIS 10.4 on Windows 10). We have tried it with the sample data you provided and it worked fine. The data we use was converted from .asc into .tif using the ArcGIS copy to raster command and the data frame as well as the data layers have the same coordinate system. We also tried to use the commend line and got an error as well.
Here are screnshots of the error messages we recieved:

![1](https://cloud.githubusercontent.com/assets/25137727/21965403/8bffb3c0-db5f-11e6-9344-547be0784553.JPG)

![2](https://cloud.githubusercontent.com/assets/25137727/21965405/90d4a306-db5f-11e6-91bf-415520ae153c.JPG)

Any help is much appreciated.

Thank you
Steven

**Comment by dtarb** [comment]
Since you say this works for the sample data, I suspect that your input data grids do not all have exactly the same number of rows and columns.  TauDEM checks for this and is supposed to write "File sizes do not match" before aborting.  In your case it looks like it is aborting prior to the message being printed.

**Comment by ThreeTone** [comment]
Hello David,
thank you for your quick reply. I checked the resolution and resampled both files to match their file size and it worked. 

Thank you,
Steven

**Comment by SvijZA** [comment]
Hello dtarb,

I also got the same error. I want to weight the contibuting area grid with a rainfall raster and I have tried to resample and I am still getting the same error
![untitled](https://user-images.githubusercontent.com/38084574/38330675-82f6194a-3851-11e8-8985-6cf27f81bd5c.png)

**Comment by dtarb** [comment]
The error message "Columns do not match:  26143  124" indicates that for your data the file BKK_Filledang.tif has 26143 columns, but bkk_rainfall_lynch_bilinear.tif has 124 columns.  You will need to figure out a way to resample bkk_rainfall_lynch_bilinear.tif to have 26143 columns to be able to use it in this function.
