### ISSUE TITLE
Utilizing TauDEM along with QGIS

### ISSUE THREAD

**Issue by epikwannabe** [dtarb/TauDEM#116]
Hello :)
I'm really new to TauDEM, and having a hard time with even starting with it. 
I installed the latest TauDEM (version 5) from the official website to use with QGIS 2.18.1.
Actually several minor problems evoked, but I thought I solved it by finding through Internet. 
Now there seems to be no problem in my log message, but still nothing works with my raster file.
Here's the example:

![image](https://cloud.githubusercontent.com/assets/26256218/23668104/645f94fe-03a3-11e7-8b2d-8ef8cf97e424.png)

Same message pops out even I develop a real file or not, so it doesn't seems to be linked to "temporary files". 

Please give me any tiny help!! It would be very thankful. 

Best Regards,
Minjung Go

**Comment by dtarb** [comment]
I am not familiar with the QGIS implementation, but one thing that worries me in your screen shot is that the input file ends in .hgt.  I am not sure what format this is, and if it is one the TauDEM GDAL library can read.

Try use the command line to debug the taudem command execution.  See http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf and other help at http://hydrology.usu.edu/taudem/taudem5/documentation.html.  By running from the command line you get better error messages and also separate possible QGIS problems from TauDEM problems.
