### ISSUE TITLE
Error 000732

### ISSUE THREAD

**Issue by herberthv** [dtarb/TauDEM#127]
Hi:
I've installed The TauDEM Tools.tbx. I have a license of ArcGIS for Desktop 10.3.
I was trying to run Dinfinity flow direction but the process failed. It reported an error 000732: "ERROR 000732: Input Raster Dataset: Dataset C:\Users\herbe\Documents\TESIS\CARTOGRAFIA\MDE\Damas2017_revARCE\dir_flujo.tif does not exist or is not supported
Failed to execute (CalculateStatistics)."
Could you help me to know the reasson of the origin of that problem? How can I fix it?
Thanks a lot.
Herberth
Costa Rica

**Comment by dtarb** [comment]
Error 000732 occurs whenever the TauDEM function fails and result files do not exist so can not be displayed.  To debug this problem we should verify that TauDEM was installed correctly and look at inputs and other messages in the output dialog.
1. Have other TauDEM functions worked successfully, or is this the first function being run.  If this is the first function, then I would be suspicious of the installation.  Did you run the full installation that sets up all libraries and paths.
2.  To check installation and get a better indication of errors, try run the program from the command line.  See http://hydrology.usu.edu/taudem/taudem5/documentation.html and the 2nd item down that is the command line guide.  The ArcGIS window should also show the command being attempted and you could cut and paste that into a command line window.
3.  If TauDEM appears to be correctly installed try it with the example data also from http://hydrology.usu.edu/taudem/taudem5/documentation.html, in case there is a problem with your data.
4.  If you are not able to find the problem please send screen shots of the input and output windows so I can see exactly what messages you are getting from the program.

**Comment by herberthv** [comment]
Excelent! Thank you. I'll follow your suggests and, if it's necessary, I'd send a print screen.
Thanks a lot.

**Comment by herberthv** [comment]
Hi:
At last, I could installed TauDEM toobox!!!!! Thank you so much!!!!

**Comment by dtarb** [comment]
Closing as appears to be answered.
