### ISSUE TITLE
Running Peuker Douglas algorithm

### ISSUE THREAD

**Issue by herberthv** [dtarb/TauDEM#129]
Hi:
I'm interested in use Peuker Douglas Algorithm to calculate the stream delineation threshold. However, I'm affraid it only could be applied if I've use D8 flow direction and D8 contributed area, since I've look at the guide to use TauDEM arcGIS Toolbox. But, if I've use D infinity, can I use Peuker Douglas function?

In any case, when I ran Peuker Douglas algorithm with my DEM pit removed, the result was wrong, I supposed. All values were zero. Could you help me to know the reason?

Thank you so much!

Herberth
<img width="960" alt="2017-05-17" src="https://cloud.githubusercontent.com/assets/28496007/26181061/4ecc73e6-3b2a-11e7-8f9f-762600c11171.png">

**Comment by dtarb** [comment]
Can you show what the inputs to the peuker douglas function were.

All stream network delineation in TauDEM uses D8 because I did not want a model that had streams spreading out.  Streams are single threaded, not multi-threaded in the data model we use.

**Comment by herberthv** [comment]
Dr. Tarboton. 
Finally, I could generate the product.
Thank you so much!
