### ISSUE TITLE
Stream Drop Not producing txt file

### ISSUE THREAD

**Issue by AndrewMcGowanCIB** [dtarb/TauDEM#132]
Hi, I have all the associated grids needed to run the Stream Drop Analysis tool. However, the tool does not produce the text file output to give me the threshold value. These errors appear 
![topoferror](https://user-images.githubusercontent.com/29263806/26902192-554b68d0-4ba6-11e7-88f0-1a471bcb7de9.PNG)

![bottomoferror](https://user-images.githubusercontent.com/29263806/26902200-57fdb8c6-4ba6-11e7-97a9-b2e04524b494.PNG)

I have made sure that the folder I am working n is not read only. And I have made sure that the Stream Drop Analysis tool is allowed past the windows firewall. Any suggestions? Thanks!

**Comment by dtarb** [comment]
I cannot see anything wrong with the input command.  Here are some things to check
1. Look at the location of points in DEM_OutletmvFinal.shp and make sure that they are at a location where values are defined in the ssa grid (and preferably greater than the upper bound - 500).  
2. Check how big the data is and if you are likely to be running out of memory.  As a rough rule you need 4 times the size of the DEM in RAM.
3 Check that the shapefile is in point format - not 3D points.
4.  Check that all other input files exist (although a file not found error would have been printed if they did not)
5.  Check that projections and rows and columns are consistent (again an error should be triggered if this is not the case)

If you are unable to find the problem, feel free to send me the data (e.g. by sharing it with me on www.hydroshare.org or some other convenient file sharing system) and I can take a look.
