### ISSUE TITLE
problem running bash Aread8 crashed.

### ISSUE THREAD

**Issue by Davidbandac** [dtarb/TauDEM#134]
Hi there, I've the following problem and I don't know how to fix it. I've unistalled anaconda and the problem persist. By the way, the result of these lines  
"mpiexec -n 8 AreaD8 -p $FO/D8FlowDir.tif -ad8 $FO/D8ContribArea.tif " 
"mpiexec -n 8 AreaDinf -ang $FO/DInfFlowAngles.tif -sca $FO/DInfContribArea.tif "

it's ok, so the problem isn't there, and I've repositioned my outlets like you suggest. 

![image](https://user-images.githubusercontent.com/29994734/27982688-0deef0b8-6377-11e7-8d69-c37b8502fe37.png)

**Comment by dtarb** [comment]
As I interpret the screen shot you have the TauDEM functions seem to have completed correctly.  This is indicated by Total Time line which only gets printed when results are written.  You should be able to find the output files on your computer.  I do not know what the function is that runs next that causes the error.  I am also puzzled by your mention of outlets as in the command lines you used with TauDEM no outlets were specified.

**Comment by Davidbandac** [comment]
the next function reads the outlets. I have specified the route that contains my shapes with the reposition using the contribution area (Aread8). So, I do not know why this tif appeared crashed. You can see my bash below.
![image](https://user-images.githubusercontent.com/29994734/27988544-dd321538-63f1-11e7-8bf7-6f86e1978685.png)

**Comment by dtarb** [comment]
Sorry to be slow replying.  I do not know your system well enough to see in the bash script what could be wrong.  I suggest you try run manually one of the aread8 functions with outlet shape file specified as the inputs.  Problems can occur with shapefiles if the projection is different, or not specified and the shapefile points are outside the domain of the grid.  Also if the shapefile is 3D TauDEM may have a problem.

**Comment by Davidbandac** [comment]
Don't worry about it, I've resolved the problem creating new outputs without properties in ArcGIS. 
Thank you anyway :)
