### ISSUE TITLE
Trouble with output file creation

### ISSUE THREAD

**Issue by JZwater** [dtarb/TauDEM#135]
I'm using QGIS 2.6.1 and TauDEM 5.3. When trying to use the Pit Remove tool i keep getting the error: "Oooops! The following output layer could not be opened".  I have made sure all of the dependencies are up to date and double checked their command paths. I am trying to create a stream reach file for watershed delineation using SWAT Editor2012.

**Comment by dtarb** [comment]
I do not know how to help with this specific error as I am not familiar with the specifics of how QGIS is using TauDEM but the general idea is that QGIS constructs a TauDEM command to submit to the system, then displays the results.  From the error it seems that the result is not being created which means the TauDEM command is not running right.  Try look for error messages that may help debug this (not sure where they would be in QGIS).  Also try run TauDEM from a command prompt directly. See http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf for how to do this.  This will help isolate any TauDEM problems separately from the interface with QGIS and SWAT editor.

A command to run pitremove should look something like
mpiexec -n 8 pitremove -z "D:\Scratch\CubDemo\cubdem" -fel "D:\Scratch\CubDemo\cubdemfel.tif"
Folders and file names will have to change to correspond to your data.

See also #19 for debugging command line issues.

**Comment by mach0** [comment]
I'd just like to add that QGIS 2.6.1 is a rather old QGIS release and QGIS has changed a lot since this.
I'd recommend using QGIS 2.18.11 (which is the current stable release) for that.
I just used 2.18.11 and Pit Remove without any problems. I remember there were some problems with the processing toolbox in earlier QGIS versions. This seems to be solved now.
