### ISSUE TITLE
Install through SCCM

### ISSUE THREAD

**Issue by joshie23** [dtarb/TauDEM#136]
I am looking to install TauDEM through SCCM. Has anyone had any success with installing it that way or by a silent install method? I am struggling given the multiple programs installed via the Tau installation process.

**Comment by dtarb** [comment]
I do not know what SCCM is and do not know how to help with this.  I suggest you look at the code for the windows installer https://github.com/dtarb/TauDEM/blob/Develop/WindowsInstaller/setup.iss to see all the dependencies, and see if based on the information there you can install each independently and silently.  It would certainly be good to have simpler and more silent installation, it is just that I do not know how to do it.

**Comment by pkdash** [comment]
Though I have not tried myself, it seems from the documentation of Inno Setup software, it should be possible to install silently passing additional arguments as suggested here:
http://www.silentinstall.org/inno_setup

Details on use of these runtime arguments can be found at http://www.jrsoftware.org/ishelp/ and then going to the Index tab.
