### ISSUE TITLE
MSMpi Install Failed - Error 1619

### ISSUE THREAD

**Issue by auniqueusernameisnotavailable** [dtarb/TauDEM#139]
During program install the setup of MSMpiSetup.exe failed with error message "MS-MPI Installation failed with error code 1619."

This happened on 2 different machines that I use (1 running Windows 7 and 1 running Windows 10). However, the same file successfully installed two other machines (both running Windows 7 in the office, so the file itself seems OK.

Because MSMpi did not install the TauDEM software does not run.

**Comment by dtarb** [comment]
This is not an error I have encountered before.  I suggest Googling the error code.  I just tried "MS-MPI Installation failed with error code 1619." and found pages that suggest it may be related to Firewall enabling, and saying where the log files are that will help you learn more.

**Comment by dtarb** [comment]
Closing - appears to be answered.
