### ISSUE TITLE
Pitremove fills entire DEM with NoData value

### ISSUE THREAD

**Issue by mankoff** [dtarb/TauDEM#140]
I've tested pitremove with a sample data set and it works fine:

    ~/Downloads/TauDEM-Develop/pitremove -z ./gsl100.tif -fel foo.tif
    gdalinfo foo.tif

The `gdalinfo` command reports, among other things, `  NoData Value=-3.00000000549775576e+38`. But when I open this GeoTIFF in GRASS GIS and display it, everything appears correct and the `min` and `max` of the DEM are `541.206` and `5206.83` respectively. Seems correct.

When I run the same `pitremove` command on a DEM that I've generated, the entire DEM has min, max, and NoData value of -3E38. My DEM GeoTIFF that I input to `pitremove` has `NoData Value=nan`. It also has a bunch of metadata:

```
  Metadata:
    COLOR_TABLE_RULE_RGB_0=2.700000e+01 3.806224e+01 68 1 84 68 2 86
    COLOR_TABLE_RULE_RGB_100=1.133676e+03 1.144738e+03 42 118 142 42 119 142
    COLOR_TABLE_RULE_RGB_101=1.144738e+03 1.155800e+03 42 119 142 42 120 142
    COLOR_TABLE_RULE_RGB_102=1.155800e+03 1.166862e+03 42 120 142 41 121 142
```

But I would be surprised if this was causing the issue, and I'm not yet sure how to remove that metadata. Is there documentation somewhere on the specific format of the GeoTIFF input to `pitremove`?

**Comment by dtarb** [comment]
TauDEM is just using GDAL to read the file.  It is not supposed to require anything special and I do noth think the metadata is involved.  I do not know how the code will handle nan as the no data value, but your experience is indicating it is not handling it right.

The relevant code (I think) is lines 160-172 of tiffIO.cpp (https://github.com/dtarb/TauDEM/blob/Develop/src/tiffIO.cpp), and specifically line 166.  An elevation grid is read into a float type by TauDEM, so there is a possibility that if your raster is not of float type that they typecasting at line 166 will lose the value or that the typecasting does not like nan.

Then internal to the pitremove function the pertinent code is at line 478 of linearpart.h.  This is the function where each data value is compared to see if it is nodata, and if it is the result is nodata.  There is a 0.00001 (1e-5) tolerance in the variable MINEPS to allow for some level of rounding, but if nan in the value for nodata causes a true return at line 476 no matter what then it would explain your result.

For the short term I would suggest you see if somehow you can coerce the no data encoding of your grid to not be nan.  Over the longer term if you are a C++ coder and want to try change/fix the code at the places indicated to accommodate your data, I could include your fix in a future release (once validated).  Alternatively you could send me the data (or a small piece of it) and I could try reproduce and fix it (but this may only occur on a time scale of months).  

Sorry that this answer is a bit technically dense.

**Comment by mankoff** [comment]
This issue goes away if the TIFFs are created with NoData = <something other than NaN>.

**Comment by dtarb** [comment]
Would you be able to send me a DEM with NoData = NaN or tell me how you created it.  Then I may be able to have the code accommodate this.

**Comment by mankoff** [comment]
I've not forgotten this ticket and your request that I look into it more. I no longer have the machine with TauDem installed and just spent time trying to install it on OS X (no luck) and gave up on the Linux VM approach because I don't have the bandwidth right now to install all the required packages (gdal, etc.).

Here is example GDAL code to set values < 0 to 0:

    gdal_calc.py -A input.tif --outfile=result.tif --calc="A*(A>0)" --NoDataValue=0

And I think the `NoDataValue` can also be set to `'NaN'` or `'nan'` based on this ticket:  https://trac.osgeo.org/gdal/ticket/6036

My TIF was generated by `r.out.gdal` from GRASS GIS. I hope this helps you create a file where you can test this. I did not thoroughly test this bug and it is possible it was elsewhere in my workflow, not TauDEM. I will look into this in more detail if I re-install TauDEM in the future.
