### ISSUE TITLE
TauDEM support instructions

### ISSUE THREAD

**Issue by mankoff** [dtarb/TauDEM#141]
According to http://hydrology.usu.edu/taudem/taudem5/support.html I'm supposed to label my question with `Question` on GitHub. I don't think that can be done if I'm not a contributor to the project (based on https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner).

Also, the link to "Support" is un-clickable on the main TauDem page: http://hydrology.usu.edu/taudem/taudem5/

**Comment by dtarb** [comment]
Thanks for pointing out these problems.  I'll have to fix them.
