### ISSUE TITLE
Streamnet tool does not extract the main river line

### ISSUE THREAD

**Issue by am2222** [dtarb/TauDEM#143]
Hi,
Thanks very much for this great tool, I am very confused with Streamnet tool as it does not extract the main river.
Here is my drep file

```
Threshold, DrainDen, NoFirstOrd,NoHighOrd, MeanDFirstOrd, MeanDHighOrd, StdDevFirstOrd, StdDevHighOrd, T
5.000000, inf, 7856, 1467, 124.936607, 210.113831, 155.536911, 207.315857, -18.176189
8.340503, inf, 4045, 674, 160.099380, 236.857559, 180.282669, 225.618301, -9.843881
13.912798, inf, 2423, 371, 177.407761, 257.587616, 190.754745, 228.794693, -7.329461
23.207947, inf, 1287, 172, 201.651901, 264.773254, 205.724762, 214.061371, -3.761131
38.713192, inf, 670, 83, 225.623886, 287.493988, 212.996338, 245.780243, -2.452258
64.577499, inf, 350, 29, 240.091431, 281.482758, 217.604568, 210.411438, -0.986747
107.721756, inf, 163, 8, 232.533737, 507.875000, 203.281403, 265.785309, -3.686591
179.690720, inf, 67, 2, 296.910461, 418.500000, 242.959122, 447.598602, -0.685279
Optimum Threshold Value: 64.577499
```

As it says 64 is optimum value, well when I run Threshold  command I get this result
<img width="922" alt="1" src="https://user-images.githubusercontent.com/4707503/30735340-7f6ad69e-9f8b-11e7-899b-bdde63f3f03e.png">

well as it shows it extracts the main rive but when I run Streamnet tool it results this 

<img width="922" alt="2" src="https://user-images.githubusercontent.com/4707503/30735390-b3b8daa4-9f8b-11e7-9701-f2f72be84e2d.png">

well were am I doing wrong? Can you please help me about this problem?
here is the list of commands which I have used
```
D8Flowdir -p 1p.tif -sd8 1sd8.tif -fel 1fel.tif

DinfFlowdir -ang 1ang.tif -slp 1slp.tif -fel 1fel.tif

AreaD8 -p 1p.tif -ad8 1ad8.tif

AreaDinf -ang 1ang.tif -sca 1sca.tif

Aread8 -p 1p.tif -o 1out.shp -ad8 1ad8o.tif
//Aread8 -p 1p.tif -ad8 1ad8o.tif

Gridnet -p 1p.tif -plen 1plen.tif -tlen 1tlen.tif -gord 1gord.tif

PeukerDouglas -fel 1fel.tif -ss 1ss.tif
//Aread8 -p 1p.tif -o 1out.shp -ad8 1ssa.tif -wg 1ss.tif
Aread8 -p 1p.tif -ad8 1ssa.tif -wg 1ss.tif

Dropanalysis -p 1p.tif -fel 1fel.tif -ad8 1ad8.tif -ssa 1ssa.tif -drp 1drp.txt -o 1out.shp -par 5 500 10 0

Threshold -ssa 1ssa.tif -src 1src.tif -thresh 64

Streamnet -fel 1fel.tif -p 1p.tif -ad8 1ad8.tif -src 1src.tif -ord 1ord3.tif -tree 1tree.dat -coord 1coord.dat -net 1net.shp -w 1w.tif 
```

thanks very much

**Comment by dtarb** [comment]
I think your problem is edge contamination.  Contributing area and similar results are being impacted by no data due to edge effects.  See http://hydrology.usu.edu/taudem/taudem5/help53/D8ContributingArea.html where this is explained.  For some functions the -nc flag will turn off edge contamination checking at the risk of your results not detecting possible problems because of edge effects.

**Comment by am2222** [comment]
@dtarb thanks for your help;
 I'll check it and let you know the result.

**Comment by am2222** [comment]
@dtarb  wow, thanks it worked
