### ISSUE TITLE
"execvp error on file" in Ubuntu

### ISSUE THREAD

**Issue by sbhadra019** [dtarb/TauDEM#145]
Hello,
I am new in using TauDEM as well as Ubuntu. I installed the TauDEM and all of it's dependencies on my Ubuntu pc. 

I ran the first command as follows to run the PitRemove function on exercise raster named "logan.tif":

`mpiexec -n 8 PitRemove logan.tif`

But I encountered following message 8-times:

> HYDU_create_process (utils/launch/launch.c:74): execvp error on file PitRemove (No such file or directory)

I am seeking help in this issue please.

**Comment by dtarb** [comment]
Perhaps a linux user like @yanliu-xsede @ahmetartu can help

**Comment by sbhadra019** [comment]
The problem is solved now. It seems that in linux the functions are installed as small case letters, e.g., pitremove, d8flowdir etc. So the following command no works in linux:
`mpiexec -n 8 pitremove logan.tif`
