### ISSUE TITLE
TWI error 000732

### ISSUE THREAD

**Issue by violleTolorza** [dtarb/TauDEM#146]
Dear David,
I could't get the TWI using the arcGIS toolbox, the error was 000732.
I've several results from taudem, both from command line and arcgis toolbox.
I try with the Dinf contributing area over an outlet and the D8 slopes from the complete dem area.
Any help is welcome,
Violeta

**Comment by dtarb** [comment]
Sorry for not answering sooner.  If this is still a problem, please send more details.
