### ISSUE TITLE
question about D-inf method

### ISSUE THREAD

**Issue by Mary-Roostaee** [dtarb/TauDEM#148]
I'd like to use the D-inf algorithm in TauDEM. I noticed that there are functions for flow direction and contributing area determination ( d-inf flow direction and d-inf contributing area, respectively). Following the tutorial, however, I could not find functions for stream and watershed delineation that use the d-infinity method outputs.  The command "Stream Reach And Watershed" need outputs from D8 method. am I missing something?

I would appreciate it if someone can help me/inform me on this matter.

Regards,
Mary
roostaee.maryam@gmail.com

**Comment by dtarb** [comment]
Stream Reach and Watershed delineation uses D8 because the data structure for representing streams assumes they are single thread and do not spread out.  Dinfinity has flow shared between down cells which would require a stream to split.  You can still use Dinifinty results as inputs to where streams start, but once streams start TauDEM follows them downhill using D8.

**Comment by Mary-Roostaee** [comment]
David,
Thank you very much for the information. 
I am using the built-in TauDEM 5 in BASINS software  (https://www.epa.gov/exposure-assessment-models/whats-changed-between-basins-40-and-41).
I managed to use output layers from D-inf method instead of D-8 ones in "Stream Reach And Watershed" command and it worked perfectly for 100m DEM. But when I tried to use DEMs with a finer resolution such as 30m, I received following error:

> TauDEM application has stopped working
[bk9fmcb1.txt](https://github.com/dtarb/TauDEM/files/1464920/bk9fmcb1.txt)

Is this error related to what you explained?
Thanks in advance.

Mary

**Comment by dtarb** [comment]
There is an error in your inputs.  It is incorrect to write 

> -p "C:\Users\mroost2\Desktop\300000\ned\30_ang.tif"

The -p flag has to refer to D8 flow directions encoded 1 to 8 that come from the D8 flow direction function.  The Dinfinity flow direction grid is encoded as angles between 0 and 2pi.  

I do not know how this worked perfectly for a 100 m DEM, but I suspect that the inputs were not the same.

There are tutorials on TauDEM and documentation for each function at http://hydrology.usu.edu/taudem/taudem5/documentation.html that could help you get an understanding of what the inputs should be for each function.

**Comment by Mary-Roostaee** [comment]
Thanks a lot
Just one other quick question;
I saw that there was a limitation on the number of cells in TauDEM 3.1: "Grid Size: Grids must be smaller than 7000 x 7000 cells" (http://hydrology.usu.edu/taudem/taudem3.1/#notes)

Is this true for latest released version as well?

**Comment by dtarb** [comment]
The 7000 x 7000 limit was overcome when we went to parallel methods.
