### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by YuxiZhang93** [dtarb/TauDEM#150]
I downloaded complete version TauDEM. Then I clicked "Yes" until the end and chose "typical". But when I added TauDEM tools.tbx in GIS arc toolbox. There is only one tool "Watershed Grid to shapefile" display, while other tools can be seen in the folder ".py" in TauDEM5Arc.

The model I am working on is water flowing out of pipeline, how it flow along the ground surface? So I thought D infinity method might be solve this. Is it fine?

**Comment by dtarb** [comment]
What version of ArcGIS are you using.  What you are seeing is not the expected behavior so something is not right.
