### ISSUE TITLE
Outdated/incomplete documentation

### ISSUE THREAD

**Issue by alexbruy** [dtarb/TauDEM#152]
Looks like documentation for TauDEM tools is not synced with latest release. For example, if I look at the
GridNetwork documentation at http://hydrology.usu.edu/taudem/taudem5/help53/GridNetwork.html I don't see any information about `-tresh` parameter, however ArcGIS tools code I see that this parameter is used together with `-mask` parameter https://github.com/dtarb/TauDEM/blob/Develop/pyfiles/GridNetwork.py.

I would be nice to add all parameters to the documentation, it will help a lot with integration TauDEM with other systems.

**Comment by dtarb** [comment]
Thanks.  I need to work on documentation.  I do actually maintain the website in a separate github repo https://github.com/dtarb/TauDEM-Website/.  If you find something simple to correct in documentation you could change the file from there and send it to me, or fork the repo and make a pull request for me to bring the change back into the master.  That would help.

**Comment by dtarb** [comment]
I have updated the gridnetwork documentation.
