### ISSUE TITLE
Linux: stream_reach_file warning: Layer creation failed.

### ISSUE THREAD

**Issue by snowman2** [dtarb/TauDEM#158]
StreamNet version 5.3.8
Input file stream_raster_grid.tif has geographic coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file flow_dir_grid_d8.tif has geographic coordinate system.
Input file contributing_area_grid_d8.tif has geographic coordinate system.
Input file elev.tif has geographic coordinate system.
Evaluating distances to outlet
Creating links
ERROR 10: Name was NULL in OGR_DS_CreateLayer
ERROR 10: Pointer 'hLayer' is NULL in 'OGR_L_CreateField'.

stream_reach_file warning: Layer creation failed.

**Comment by snowman2** [comment]
Build log for streamnet:

TauDEM/src/streamnet.cpp: In function ‘int reachshape(long int*, float*, float*, float*, double*, double*, long int, tiffIO&)’:
TauDEM/src/streamnet.cpp:334:46: warning: ignoring return value of ‘OGRErr OGR_L_CreateFeature(OGRLayerH, OGRFeatureH)’, declared with attribute warn_unused_result [-Wunused-result]
     OGR_L_CreateFeature( hLayer1, hFeature1 ); //adding feature

**Comment by snowman2** [comment]
gdalinfo --version
GDAL 2.2.2, released 2017/09/15

**Comment by snowman2** [comment]
OGR_DS_CreateLayer -> deprecated. See: http://www.gdal.org/ogr__api_8h.html#a424d383a37fbeaea58acaea11717f320

**Comment by snowman2** [comment]
This is also suspect:

[  2%] Building CXX object CMakeFiles/streamnet.dir/commonLib.cpp.o
TauDEM/src/commonLib.cpp: In function ‘char* getLayername(char*)’:
/TauDEM/src/commonLib.cpp:399:10: warning: address of local variable ‘layername’ returned [-Wreturn-local-addr]
     char layername[MAXLN];

**Comment by dtarb** [comment]
see https://github.com/hydroshare/hydroshare-jupyterhub/issues/113 and perhaps @yanlui-chn can comment.  If the two of you can figure out how to fix this, I'd be happy to include the fixed code.  My linux capability is limited.

**Comment by snowman2** [comment]
mpicxx --version 
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by dtarb** [comment]
I believe this was fixed with the commit 951ed55 on Nov 18 https://github.com/dtarb/TauDEM/commits/Develop/src/streamnet.cpp.  See #93 and at the end of #154
