### ISSUE TITLE
create_outletmn.cpp is not in src directory

### ISSUE THREAD

**Issue by molinero2** [dtarb/TauDEM#159]
Hello
I having a trouble during cmake configuration.

CMake Error at CMakeLists.txt:91 (add_executable):
  Cannot find source file:

    create_outletmn.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
 
I downloaded the master release in the github repository, and the create_outletmn.cpp is not the src directory.
Do I have to comment the line in the cmake file where create_outletmn.cpp file is require? Or how can I solve the problem?

Thanks

**Comment by dtarb** [comment]
I think that is experimental code that was removed.  Try comment the line (or delete it).   Sorry, I trusted the CMakeLists.txt I got given, as I do not use linux.

**Comment by molinero2** [comment]
To install Taudem in GNU/Linux Debian you can download installation script from: taudem_ubuntu.tar.bz2

in this link:

https://unix.stackexchange.com/questions/346775/how-to-solve-building-error-where-a-variable-was-not-declared-in-this-scope
