### ISSUE TITLE
Detect possible landslide areas from 30m DEM

### ISSUE THREAD

**Issue by siriomod** [dtarb/TauDEM#162]
I am writing you to ask for a possible Landslide detection workflow considering TauDEM on ARCGIS 10.4

Is it viable detect probable landside areas (detachment, flow, deposition areas) considering 30m DEM?
We are working on erosion propensity analysis by RUSLE equation at global scale. 
Now in the hot spot areas we want to perform some specific analysis like the detection of possible landslide areas.
We are using the “D-Infinity reverse accumulation” to detect possible instable slope but the result doesn’t match with a photointerpretation check. 
To achieve the “D-Infinity reverse accumulation” we are using as inputs:
- “Flow direction grid raster”; 
- “Weight grid” (represented by DEM 30m from SRTM).

My questions are:
-	Is “D-Infinity reverse accumulation” the most appropriate tool to detect landslide?
-	Could “Weight grid” be represented by DEM info?
-	Which is the correct workflow to detect possible Landslide areas?

Thanks for your support

**Comment by dtarb** [comment]
Look at the SINMAP stability index tool http://hydrology.usu.edu/taudem/taudem5/help53/StabilityIndex.html.  To understand the theory read http://hydrology.usu.edu/sinmap2/.  The SINMAP code at the sinmap2 website is a bit deprecated as we have not been able to advance it to keep up with ArcGIS changes, but the gist of the algorithm is implemented in the TauDEM function.

**Comment by siriomod** [comment]
Thanks for the prompt reply,
I will explore your suggestions,
Best regards
