### ISSUE TITLE
D-Infinity Avalanche Runout aborted

### ISSUE THREAD

**Issue by briochamsley** [dtarb/TauDEM#163]
Good day,
I'm trying to run a D-Infinity Avalanche Runout analysis. As Inputs I used the Pit-Removed-dtm raster and the output of the D-Infinity Flow Directions Output with the automatic created names. I also named the Avalanche Source Site Grit the same way with "ass" at the end. That file used a long-integer field before, but I calculated a short-integer field and deleted the long integer field.
But whenever I run it I get the following error:

"
job aborted:
[ranks] message

[0] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 0

[1] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 1

[2] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 2

[3] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 3

[4] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 4

[5] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 5

[6] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 6

[7] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 5, comm rank 7

---- error analysis -----

[0-7] on LAPTOP-ONEDRIVE
DinfAvalanche aborted the job. abort code 5

---- error analysis -----

Calculate Statistics

Failed script DInfAvalancheRunout...

Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\DinfAvalancheRunout.py", line 71, in <module>
    arcpy.CalculateStatistics_management(rz)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\management.py", line 14618, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset E:\Dokumente\Uni\HD - Sem5\FortGIS\GISFortAbschluss\Abschluss\Daten\Untersuchungsgebiet\dgmUG0rz.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

Failed to execute (DInfAvalancheRunout).
Failed at Wed Feb 28 20:19:19 2018 (Elapsed Time: 9,93 seconds)
"

Does anyone what that means and has any Idea what the reason could be?
Thanks in advance
Jo

**Comment by dtarb** [comment]
The most likely problem (and the one that generates this error 5) is file sizes not matching.  Check that the rows, columns and cell size of fel ang and ass files are all the same.  The ass one is the most likely to be different as you created it yourself.

(For what it is worth, I have fixed up error reporting in the code so that in future releases this error will be better reported)
