### ISSUE TITLE
TauDEM

### ISSUE THREAD

**Issue by Mostafa-ebrahimi** [dtarb/TauDEM#165]
What is the application of TauDem in landslide Detection

**Comment by dtarb** [comment]
See http://hydrology.usu.edu/sinmap2/.  This describes the SINMAP theory and model for shallow landslide risk.  That specific code implementation is old, but the TauDEM stability index tools, see http://hydrology.usu.edu/taudem/taudem5/help53/SINMAPStabilityIndexToolserOverview.htm and http://hydrology.usu.edu/taudem/taudem5/help53/StabilityIndex.html implement the methodology in TauDEM.

**Comment by Mostafa-ebrahimi** [comment]
Hi David,
Thank you very much
