### ISSUE TITLE
SetRegion.cpp fails to compile on Ubuntu

### ISSUE THREAD

**Issue by jgrn307** [dtarb/TauDEM#166]
I'm trying to get TauDEM compiled on Ubuntu Xenial, and after the make, I get this error:

```
[  0%] Building CXX object CMakeFiles/setregion.dir/SetRegionmn.cpp.o
/home/vagrant/TauDEM/src/SetRegionmn.cpp: In function ‘int main(int, char**)’:
/home/vagrant/TauDEM/src/SetRegionmn.cpp:108:1: error: jump to label ‘errexit’ [-fpermissive]
 errexit:
 ^
/home/vagrant/TauDEM/src/SetRegionmn.cpp:55:23: note:   from here
    if(argc <= 2) goto errexit;
                       ^
/home/vagrant/TauDEM/src/SetRegionmn.cpp:56:9: note:   crosses initialization of ‘int i’
     int i=1; 
         ^
CMakeFiles/setregion.dir/build.make:62: recipe for target 'CMakeFiles/setregion.dir/SetRegionmn.cpp.o' failed
make[2]: *** [CMakeFiles/setregion.dir/SetRegionmn.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/setregion.dir/all' failed
make[1]: *** [CMakeFiles/setregion.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Any ideas?

Edit: I'm using the Develop branch from git.

**Comment by dtarb** [comment]
You might try move the int i=1; line to above if(argc <= 2) goto errexit; line.  The rationale for this is the error seems to relate to initialization of i, which seems to be being flagged as an error.  If that fails you could restructure the conditional logic a bit to avoid the first goto.   (Looking at this now, I do acknowledge that the logic involving the goto is not structured perfectly, and probably does not follow modern structured programming standards well, so there is opportunity for improvement, that may resolve the compiler complaint).

**Comment by smnorris** [comment]
Any luck? I tried moving the `int i=1` line as recommended but got below message instead.

I've been able to compile and install with the script linked [here](https://unix.stackexchange.com/questions/346775/how-to-solve-building-error-where-a-variable-was-not-declared-in-this-scope), but it seems to be a very old version (5.0.6).

```
~/temp/TauDEM/src/build$ make
Scanning dependencies of target setregion
[  0%] Building CXX object CMakeFiles/setregion.dir/SetRegionmn.cpp.o
[  1%] Building CXX object CMakeFiles/setregion.dir/SetRegion.cpp.o
/home/snorris/temp/TauDEM/src/SetRegion.cpp: In function ‘int setregion(char*, char*, char*, long int)’:
/home/snorris/temp/TauDEM/src/SetRegion.cpp:152:40: error: call of overloaded ‘setData(long int&, long int&, long int&)’ is ambiguous
         newvals->setData(i, j, regionID);
                                        ^
In file included from /home/snorris/temp/TauDEM/src/linearpart.h:42:0,
                 from /home/snorris/temp/TauDEM/src/commonLib.h:102,
                 from /home/snorris/temp/TauDEM/src/SetRegion.cpp:52:
/home/snorris/temp/TauDEM/src/partition.h:117:19: note: candidate: virtual void tdpartition::setData(long int, long int, int16_t)
      virtual void setData(long, long, int16_t){}
                   ^
/home/snorris/temp/TauDEM/src/partition.h:118:16: note: candidate: virtual void tdpartition::setData(long int, long int, int32_t)
   virtual void setData(long, long, int32_t){}
                ^
/home/snorris/temp/TauDEM/src/partition.h:119:16: note: candidate: virtual void tdpartition::setData(long int, long int, float)
   virtual void setData(long, long, float){}
                ^
/home/snorris/temp/TauDEM/src/SetRegion.cpp:159:37: error: call of overloaded ‘setData(long int&, long int&, long int&)’ is ambiguous
      newvals->setData(i, j, regionID);
                                     ^
In file included from /home/snorris/temp/TauDEM/src/linearpart.h:42:0,
                 from /home/snorris/temp/TauDEM/src/commonLib.h:102,
                 from /home/snorris/temp/TauDEM/src/SetRegion.cpp:52:
/home/snorris/temp/TauDEM/src/partition.h:117:19: note: candidate: virtual void tdpartition::setData(long int, long int, int16_t)
      virtual void setData(long, long, int16_t){}
                   ^
/home/snorris/temp/TauDEM/src/partition.h:118:16: note: candidate: virtual void tdpartition::setData(long int, long int, int32_t)
   virtual void setData(long, long, int32_t){}
                ^
/home/snorris/temp/TauDEM/src/partition.h:119:16: note: candidate: virtual void tdpartition::setData(long int, long int, float)
   virtual void setData(long, long, float){}
                ^
/home/snorris/temp/TauDEM/src/SetRegion.cpp:162:35: error: call of overloaded ‘setData(long int&, long int&, long int&)’ is ambiguous
     newvals->setData(i, j,regionID);
                                   ^
In file included from /home/snorris/temp/TauDEM/src/linearpart.h:42:0,
                 from /home/snorris/temp/TauDEM/src/commonLib.h:102,
                 from /home/snorris/temp/TauDEM/src/SetRegion.cpp:52:
/home/snorris/temp/TauDEM/src/partition.h:117:19: note: candidate: virtual void tdpartition::setData(long int, long int, int16_t)
      virtual void setData(long, long, int16_t){}
                   ^
/home/snorris/temp/TauDEM/src/partition.h:118:16: note: candidate: virtual void tdpartition::setData(long int, long int, int32_t)
   virtual void setData(long, long, int32_t){}
                ^
/home/snorris/temp/TauDEM/src/partition.h:119:16: note: candidate: virtual void tdpartition::setData(long int, long int, float)
   virtual void setData(long, long, float){}
                ^
CMakeFiles/setregion.dir/build.make:86: recipe for target 'CMakeFiles/setregion.dir/SetRegion.cpp.o' failed
make[2]: *** [CMakeFiles/setregion.dir/SetRegion.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/setregion.dir/all' failed
make[1]: *** [CMakeFiles/setregion.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by smnorris** [comment]
update - I compiled 5.3.7 on Ubuntu 16.04 with no issues using this as a guide:

https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/taudem.rb

**Comment by dtarb** [comment]
Thanks for letting me know.  Setregion is a new utility function to edit a raster, not part of any general work sequence, and I added it after version 5.3.7.  You may be OK with version 5.3.7, or if you need specific functionality beyond 5.3.7 you could just omit Setregion from the compile.

**Comment by Sergio71** [comment]
Hello!

I am struggling to install TauDem in a Debian/Linux. I believe It is a similar problem of smnorris.

**error output:**

_Scanning dependencies of target setregion
[  0%] Building CXX object CMakeFiles/setregion.dir/SetRegionmn.cpp.o
/usr/local/src/TauDEM-Develop/src/SetRegionmn.cpp: In function ‘int main(int, char**)’:
/usr/local/src/TauDEM-Develop/src/SetRegionmn.cpp:108:1: error: jump to label ‘errexit’ [-fpermissive]
 errexit:
 ^~~~~~~
/usr/local/src/TauDEM-Develop/src/SetRegionmn.cpp:55:23: note:   from here
    if(argc <= 2) goto errexit;
                       ^~~~~~~
/usr/local/src/TauDEM-Develop/src/SetRegionmn.cpp:56:9: note:   crosses initialization of ‘int i’
     int i=1;
         ^
CMakeFiles/setregion.dir/build.make:62: recipe for target 'CMakeFiles/setregion.dir/SetRegionmn.cpp.o' failed
make[2]: *** [CMakeFiles/setregion.dir/SetRegionmn.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/setregion.dir/all' failed
make[1]: *** [CMakeFiles/setregion.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2_

Tks!

**Comment by dtarb** [comment]
I have just updated the compiling of TauDEM on Ubuntu Linux, both make and cmake in the Develop branch.  See if the updates work for you.  I will close this issue, but if you have trouble again, feel free to reopen or post another one.
