### ISSUE TITLE
File locking failed in ADIOI_Set_lock(fd 4,cmd F_SETLKW/7,type F_RDLCK/0,whence 0) with return value FFFFFFFF and errno 26

### ISSUE THREAD

**Issue by tmakosa** [dtarb/TauDEM#17]
Hie i need help am having an error when i try to compile my taudem 5.1 on an HPC Cluster.See below the command and errors am getting

[sirdc@ln01 ~]$ mpiexec -n 4 /lustre/softs/taudem/taudem-5.1/build/pitremove -z ./dem -fel ./demfel 
PitRemove version 5.1
File locking failed in ADIOI_Set_lock(fd 4,cmd F_SETLKW/7,type F_RDLCK/0,whence 0) with return value FFFFFFFF and errno 26.
- If the file system is NFS, you need to use NFS version 3, ensure that the lockd daemon is running on all the machines, and mount the directory with the 'noac' option (no attribute caching).
- If the file system is LUSTRE, ensure that the directory is mounted with the 'flock' option.
ADIOI_Set_lock:: Function not implemented
ADIOI_Set_lock:offset 0, length 2
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
File locking failed in ADIOI_Set_lock(fd 4,cmd F_SETLKW/7,type F_RDLCK/0,whence 0) with return value FFFFFFFF and errno 26.
- If the file system is NFS, you need to use NFS version 3, ensure that the lockd daemon is running on all the machines, and mount the directory with the 'noac' option (no attribute caching).
- If the file system is LUSTRE, ensure that the directory is mounted with the 'flock' option.
ADIOI_Set_lock:: Function not implemented
ADIOI_Set_lock:offset 0, length 2
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
File locking failed in ADIOI_Set_lock(fd 4,cmd F_SETLKW/7,type F_RDLCK/0,whence 0) with return value FFFFFFFF and errno 26.
- If the file system is NFS, you need to use NFS version 3, ensure that the lockd daemon is running on all the machines, and mount the directory with the 'noac' option (no attribute caching).
- If the file system is LUSTRE, ensure that the directory is mounted with the 'flock' option.
ADIOI_Set_lock:: Function not implemented
ADIOI_Set_lock:offset 0, lFile locking failed in ADIOI_Set_lock(fd 4,cmd F_SETLKW/7,type F_RDLCK/0,whence 0) with return value FFFFFFFF and errno 26.
- If the file system is NFS, you need to use NFS version 3, ensure that the lockd daemon is running on all the machines, and mount the directory with the 'noac' option (no attribute caching).
- If the file system is LUSTRE, ensure that the directory is mounted with the 'flock' option.
ADIOI_Set_lock:: Function not implemented
ADIOI_Set_lock:offset 0, length 2
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
ength 2
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
rank 2 in job 3  ln01_56636   caused collective abort of all ranks
  exit status of rank 2: return code 1 
rank 1 in job 3  ln01_56636   caused collective abort of all ranks
  exit status of rank 1: return code 1 
rank 0 in job 3  ln01_56636   caused collective abort of all ranks
  exit status of rank 0: return code 1

**Comment by dtarb** [comment]
I do not know how to interpret and help you with these LUSTRE file system errors.  However the following may help

* Check that you are using a version of TauDEM consistent with your inputs.  You have specified inputs as folders "dem" and "demfel", but version 5.1 of TauDEM uses single tiff files as inputs.  The version that worked with multiple files is supposed to be numbered 5.2 (though depending on where you got the source you are using this may not be consistent)
* Consider using the latest version (5.3) that uses GDAL library for IO.  This should be more reliable than the tiffio library we wrote that does not handle all variants of tiff input files.

**Comment by tmakosa** [comment]
Thanks dtarb let me try use version 5.3 with GDAL

**Comment by dtarb** [comment]
I assume you have this figured out by now so am closing.
