### ISSUE TITLE
Slope

### ISSUE THREAD

**Issue by jvalenza** [dtarb/TauDEM#170]
New to TauDEM, and I just had a quick question about the slope file that is used for flow direction. In what units are the d8Slope values? I am hoping to use the values in the d8Slope file (as calculated for my AOI) as the hillslope angle values, (assuming that the two are equivalent), but I need to know what units the d8Slope values are in before I can convert to degrees. When I open the file in ArcMap the range in values is 0 to 452400... and I'm not sure how to interpret this. 

Thanks!
J

**Comment by dtarb** [comment]
Sorry to be slow in replying.  Slope values are rise over run, or since it is downhill, the vertical drop over horizontal distance.  This is equivalent to the tan of the angle.
