### ISSUE TITLE
Help in interpolating output of D-infinity Contributing Area

### ISSUE THREAD

**Issue by Nahal2** [dtarb/TauDEM#171]
![d-infinity](https://user-images.githubusercontent.com/36236554/40186919-3e49e6e8-59c4-11e8-9942-74e7a45503be.JPG)
Hello,

The output raster of D-infinity Contributing Area includes: Rowid, Value, and Count. I'm interested to calculate the number of cells that contribute into a specific cell. How can I get that from the raster output?
For example when: Value=10 and Count=412 what it means?

**Comment by dtarb** [comment]
This table means that 412 cells have a value of 10, 17 cells have a value of 11, 20 cells have a value of 12 and so on.  The output from D-Infinity contributing area is a floating point grid where the value represents the specific catchment area which is contributing area (number of cells *dx*dy) divided by cell size (dx or dy). Cell size represents the "contour length" in the definition of specific catchment area.  See http://hydrology.usu.edu/taudem/taudem5/help53/DInfinityContributingArea.html where I explain this a bit more.

It seems to me that you have converted the floating point grid that TauDEM outputs to have this value attribute table, which has rounded the values and produced the rowid and count values, which are not very meaningful in interpreting the results.
