### ISSUE TITLE
The links for GDAL on download page are broken

### ISSUE THREAD

**Issue by nsoonhui** [dtarb/TauDEM#175]
Referring to [this page](http://hydrology.usu.edu/taudem/taudem5/downloads.html).

The 

1.  GDAL 201 (MSVC 2013) for 32 bit Windows PC
2. GDAL 201 (MSVC 2013 Win 64) for 64 bit Windows PC

links are broken. Can they be fixed?

**Comment by dtarb** [comment]
The packages actually used to develop the TauDEM executables are no longer at the URL's where I retrieved them from .  I will have to investigate, and probably should update TauDEM to compile against more recent binaries.  

Archives for GDAL packages are at http://gisinternals.com/archive.php, however I am unable to find current links to the exact files I used.

If you are compiling/building TauDEM now, I would suggest trying one of the most recent stable releases at http://gisinternals.com/release.php and then attempt to address any compatibility issues that come up.

**Comment by nsoonhui** [comment]
I've tried the [latest release](http://gisinternals.com/release.php) GDAL 2.3.0 and MapServer 7.0.7, and they are working fine on 64 and 32 bit machine.

You can safely link to that.

**Comment by dtarb** [comment]
Thanks.  I updated the website
