### ISSUE TITLE
TauDEM 5.3 - Error connecting to the Service

### ISSUE THREAD

**Issue by fbiles** [dtarb/TauDEM#18]
Hello -

I just downloaded and installed the latest version of TauDEM (Nov 12, 2015), TauDEM530_prerelease.exe.  I'm running Windows7. In the command window I entered the following:

mpiexec -n 8 DinfFlowDir -fel "E:\ddrive\GIS\projects\DEM_Fil.tif" -ang "E:\ddrive\GIS\projects\DEM_Tauang.tif" -slp "E:\ddrive\GIS\projects\DEM_Tauslp.tif"

and received the following error messages:

Error connecting to the Service
[mpiexec@PCxxxxxxxxx] ..\hydra\utils\sock\sock.c (270): unable to connect from "
PCxxxxxxxxx" to "PCxxxxxxxxx" (No error)
read from stdin failed, error 6.
[mpiexec@PCxxxxxxxxx] ..\hydra\tools\demux\demux_select.c (78): select error (No
 such file or directory)
[mpiexec@PCxxxxxxxxx] ..\hydra\pm\pmiserv\pmiserv_pmci.c (480): error waiting fo
r event
[mpiexec@PCxxxxxxxxx] ..\hydra\ui\mpich\mpiexec.c (945): process manager error w
aiting for completion

Any ideas how I can resolve these errors?
Thank you.

**Comment by nazmussazib** [comment]
Which MPI library are you using? For TauDEM we have used Microsoft HPC . I guess you are using different MPI library (may be intel MPI) . As i run your command with different input it works fine for me.

**Comment by dtarb** [comment]
The Microsoft HPC library should have been installed with the version you downloaded.  However there is a possibility that you have a conflicting version from somewhere else that is ahead of the Microsoft MPI on the path.  The paths you report suggest that some "hydra" may be the problem.  At a command window type path to examine the path.  You could also type "where mpiexec" at the command prompt to discover all mpiexec programs on your computer and if the first one is not the path to Microsoft HPC Pack, something like "C:\program files\Microsoft HPC Pack 2012\bin\mpiexec.exe" then that may indicate the issue.  In this case try typing 
"C:\program files\Microsoft HPC Pack 2012\bin\mpiexec.exe" -n 8 ...  
to run the programs.

**Comment by fbiles** [comment]
That was it - thank you! 
Typing "where mpiexec" returned:
E:\ddrive\GIS\projects\WaterTableModel\CSC\fbiles_working_layers>where mpiexec
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\mpirt\mpiexec.exe
C:\Program Files\Microsoft HPC Pack 2012\Bin\mpiexec.exe

So as you suggested I typed "C:\program files\Microsoft HPC Pack 2012\bin\mpiexec.exe" -n 8 ...
and the program appears to be running normally.
