### ISSUE TITLE
ERROR 000732: Input Raster Dataset

### ISSUE THREAD

**Issue by sandhyageo** [dtarb/TauDEM#19]
I download and installed TauDEM for examining the capability of the tool to edit the DEM. I extracted and imported the elevation to ArcMap and ran the 'pit remove' tool. When it finished running it shows error message;

Process started:

Executing: Calculate Statistics

Failed script PitRemove...

Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\PitRemove.py", line 63, in <module>
    arcpy.CalculateStatistics_management(outFile)
  File "c:\program files (x86)\arcgis\desktop10.2\arcpy\arcpy\management.py", line 13825, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset: Dataset D:\work\projects\test\Demo\cubdemfel.tif does not exist or is not supported
Failed to execute (CalculateStatistics).

Failed to execute (PitRemove).

I could not process further. Any help would be greatly appreciated. 

Regards,
Sandhya

**Comment by dtarb** [comment]
This can occur if MPI is not properly installed or paths are not correct from the install.  Try the following:

1. Check above the line Process started: in the message box.  You should see something like
Command Line: mpiexec -n 8 pitremove -z "D:\Scratch\CubDemo\cubdem" -fel "D:\Scratch\CubDemo\cubdemfel.tif"
Open a command prompt and type this in  starting from "mpiexec" and see if it works.  This should run the program.  If there are errors you should be able to see them and perhaps act on them.

2. The command line guide http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf has additional information on running from the command line and what the paths should be.

3.  At a command prompt, the path command should show you the path, and the commands "where mpiexec" and "where pitremove" should show you whether and where on your installation these functions that TauDEM uses have been installed and if they are correct.  The path can be edited from "advanced system settings" (type advanced in the start search and select this), Then select environment variables and find path under system variables.

**Comment by sandhyageo** [comment]
Thanks dtarb,

It worked for me.

**Comment by RondaStrauch** [comment]
I also have this error, but I'm not as computer savoy to figure out what you mean above for the solution.  I just uninstalled and updated TauDEM to 5.3.5 today.  I'm trying to use pitfill or D-infinity tools, but this error (the same one above) just keeps coming up.  I've located my mpiexec file and it was in the C:\Program Files\Microsoft HPC Pack 2012\Bin.  I copied it to the TauDEM5Exe folder, but that didn't seem to solve the problem.  Where is "advance system settings" that I need to edit the "path"

Any help would be most appreciated.  Thanks!!!

**Comment by dtarb** [comment]
I can not see anything wrong with the paths.  Check that there are no trailing spaces that sometimes cause problems.  If you type "path" at the command prompt do you see the path correctly.

Copying an exe file to a different location is generally not a good idea as it may have other dependencies, so I suggest leaving it where it was.  Did you type "where gdal111.dll" or "where gdal111.gll" as you wrote above.  The typo "g" would explain where not finding it, but still does not explain why this does not work for you.  

Did you reboot the computer after the path changes.  They may not take effect on programs that are already running and rebooting makes sure everything gets restarted.

**Comment by RondaStrauch** [comment]
Yes...this worked!!  I likely had a typo and I restarted my machine.  Now the gdal file is present and the TauDEM tool worked fine.  Thanks for helping on this so quickly!

**Comment by danielalthoff** [comment]
> This can occur if MPI is not properly installed or paths are not correct from the install. Try the following:
> 
> 1. Check above the line Process started: in the message box.  You should see something like
>    Command Line: mpiexec -n 8 pitremove -z "D:\Scratch\CubDemo\cubdem" -fel "D:\Scratch\CubDemo\cubdemfel.tif"
>    Open a command prompt and type this in  starting from "mpiexec" and see if it works.  This should run the program.  If there are errors you should be able to see them and perhaps act on them.
> 2. The command line guide http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf has additional information on running from the command line and what the paths should be.
> 3. At a command prompt, the path command should show you the path, and the commands "where mpiexec" and "where pitremove" should show you whether and where on your installation these functions that TauDEM uses have been installed and if they are correct.  The path can be edited from "advanced system settings" (type advanced in the start search and select this), Then select environment variables and find path under system variables.

when i type in cmd : 
C:\Users\danie>where mpiexec
C:\Program Files\Microsoft MPI\Bin\mpiexec.exe      -- THIS IS OK

C:\Users\danie>where pitremove
INFO: Could not find files for the given pattern(s).     -- WHY WONT IT FIND IT? I cant fix this

**Comment by danielalthoff** [comment]
> This means that the path to where the TauDEM functions are has not been set. The typical location is C:\Program Files\TauDEM\TauDEM5Exe and this needs to be on your path. This should have been done by the installer, but if you did not have permissions to change paths, or did not have the set path box checked, it may not have been set. As noted above the path can be edited from "advanced system settings". Type advanced in the start search and select this, Then select environment variables and find path under system variables and create a new entry with the path to the location of the files on your system.

Thank you very much.
At first when I searched for "advanced system settings"  it only showed "view advanced system settings".
I openned it but didn't find the "Environment variables".... I had been sleep deprived... my bad
And thanks again. Worked perfectly

**Comment by dtarb** [comment]
See my response in https://github.com/dtarb/TauDEM/issues/192#issuecomment-444906672

**Comment by micpy** [comment]
Same error in ArcMap.
However, a different issue was raised when I tried to execute it in cmd.

"PitRemove.exe - Entry Point Not Found" [TauDEM537]
![image](https://user-images.githubusercontent.com/64643054/83198984-e5162980-a172-11ea-8611-7fd5a51006cb.png)
 
Note:
I experienced the same error with TauDEM535
My unit is 64-bit.
I already added to my Path the following: C:\Program Files\Microsoft MPI\Bin\mpiexec.exe;C:\Program Files\Microsoft HPC Pack 2012\Bin\mpiexec.exe;C:\Program Files\GDAL;C:\Program Files\Microsoft HPC Pack 2012;C:\Program Files\TauDEM;C:\Program Files\TauDEM\TauDEM5Exe

**Comment by YonniYe** [comment]
I tried to use TauDEM in arcmap either, and I met the same question with you. 
My solution is to **set parellel processing number to 0 in environment settings**:
![image](https://user-images.githubusercontent.com/62197564/111964124-3abb2880-8b2f-11eb-8e9a-1047389472a1.png)

**Comment by realmzoer15** [comment]
![image](https://user-images.githubusercontent.com/106179291/170097448-cb498e01-65ce-4717-9aef-694033baa614.png)
do you know with this ?

**Comment by RondaStrauch** [comment]
No...it's been too many years since I've worked in GIS with DEMs. Sorry.

**Comment by dtarb** [comment]
@RondaStrauch I saw this comment, but am not sure what the problem is that you are referring to.  If you tell me a bit more I may be able to help.

**Comment by RondaStrauch** [comment]
@realmzoer15, can you share your problem with David? I just responded in email and it doesn't track your original image on the avalanche runout algorithm.
