### ISSUE TITLE
The software used to render the catchment delineation

### ISSUE THREAD

**Issue by WindingWinter** [dtarb/TauDEM#191]
In the [Taudem command line guide](http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf), I wonder what software you use to render the catchment delineation?

![catchment_streamline](https://user-images.githubusercontent.com/13161574/49362977-58c0ad00-f71b-11e8-927f-e14d6f624f54.png)

It looks very nice.

**Comment by dtarb** [comment]
The above was rendered with ArcGIS.
