### ISSUE TITLE
Different Threshold value might produce "holes" in the catchment

### ISSUE THREAD

**Issue by WindingWinter** [dtarb/TauDEM#194]
By using the default `Logan.tiff` file and run the following command:

```
1. PitRemove.exe Logan.tif
2. D8FlowDir.exe -p Logan.tif -sd8 Logansd8.tif -fel Loganfel.tif
3. aread8.exe -p Loganp.tif -ad8 Loganad8.tif
4. Gridnet.exe -p Loganp.tif -plen Loganplen.tif -tlen Logantlen.tif -gord Logangord.tif
5. PeukerDouglas.exe -fel Loganfel.tif -ss Loganss.tif
6. aread8.exe -p Loganp.tif -wg Loganss.tif -ad8 Loganssa.tif
7.  Threshold.exe -ssa Loganssa.tif -src Logansrc.tif -thresh %threshold_val%
8.  Streamnet.exe -fel Loganfel.tif  -p Loganp.tif  -ad8 Loganad8.tif -src Logansrc.tif -ord Loganord.tif -tree Logantree.dat -coord Logancoord.dat -net Logannet.shp -w Loganw.tif
```

I found that the catchment produced is different for different value of `%threshold_val%`:

![threshold50](https://user-images.githubusercontent.com/13161574/50198244-ada02c80-0385-11e9-8151-ef3dc7ce8078.png)
This is for the case where  `%threshold_val%=50`

![threshold150](https://user-images.githubusercontent.com/13161574/50198258-bb55b200-0385-11e9-8481-d3f257c0910f.png)
This is for the case where  `%threshold_val%=150`

![threshold300](https://user-images.githubusercontent.com/13161574/50198264-c14b9300-0385-11e9-93d8-55e7277371ef.png)
This is for the case where  `%threshold_val%=300`

I can understand the streamlines or even the outline shapes of the catchments are different when you use different `%threshold_val%`, but I can't understand why in some cases, there are missing catchments? ( as for the case for `50` and `150`)?

**Comment by dtarb** [comment]
I think the internal holes you are seeing are an artifact of whatever visualization you are using.  Here is the result I get

For 50
![image](https://user-images.githubusercontent.com/3456833/50199139-7c374a80-030c-11e9-944a-34f65c77ae60.png)

For 150
![image](https://user-images.githubusercontent.com/3456833/50199155-8e18ed80-030c-11e9-907e-f720a69248c4.png)

Along the edges you expect differences as if a stream leaves the domain with ssa value between 50 and 150 it will be mapped at 50 threshold, but not at 150 threshold, resulting in that catchment being out of the domain.  But internal holes should not occur (unless you do not fill pits).

**Comment by WindingWinter** [comment]
@dtarb , I double check my rendering engine and it seems to be OK... I attach my `loginw.tiff` file here, would you like to attach yours so that we can cross compare?

[Loganw.zip](https://github.com/dtarb/TauDEM/files/2693597/Loganw.zip)

**Comment by WindingWinter** [comment]
I guess I know why-- the output from taudem is correct, what is not correct when I convert the raster output from taudem to vector via `gdal.polygonize`. There must be a bug in `gdal.polygonize`. Will try to scale down and file the problem later.
