### ISSUE TITLE
Unable to get the "correct streamlines"

### ISSUE THREAD

**Issue by WindingWinter** [dtarb/TauDEM#204]
Try the below configuration:

```
PitRemove.exe "WATERSHED TESTING2.tif"
D8FlowDir.exe -p  "WATERSHED TESTING2p.tif" -sd8 "WATERSHED TESTING2sd8.tif" -fel "WATERSHED TESTING2fel.tif"
aread8.exe -p  "WATERSHED TESTING2p.tif" -ad8 "WATERSHED TESTING2ad8.tif" -wg "WATERSHED TESTING2ss.tif"
gridnet.exe -p "WATERSHED TESTING2p.tif" -plen "WATERSHED TESTING2plen.tif" -tlen "WATERSHED TESTING2tlen.tif" -gord "WATERSHED TESTING2gord.tif"
peukerdouglas.exe -fel "WATERSHED TESTING2fel.tif" -ss "WATERSHED TESTING2ss.tif"
aread8.exe  -p  "WATERSHED TESTING2p.tif" -ad8  "WATERSHED TESTING2ssa.tif" -wg " "WATERSHED TESTING2ss.tif""
Threshold.exe -ssa "WATERSHED TESTING2ssa.tif" -src "WATERSHED TESTING2src.tif" -threshold 50
streamnet.exe -fel  "WATERSHED TESTING2fel.tif" -p "WATERSHED TESTING2p.tif" -ad8 "WATERSHED TESTING2ad8.tif" -src "WATERSHED TESTING2src.tif" -ord "WATERSHED TESTING2ord.tif" -tree "WATERSHED TESTING2tree.dat" -coord "WATERSHED TESTING2coord.dat" -net "WATERSHED TESTING2net.shp" -w "WATERSHED TESTING2w.tif"
```

The output is very different from what we can see on manual inspection.

From 3D view, it seems that the streamlines mostly flow across from top left to bottom right or vice versa. 

![3d flow direction](https://user-images.githubusercontent.com/13161574/57686615-7a2fa880-766c-11e9-8967-2f682137f673.png)

But the output generated by TauDEM seems to indicate that the flow goes in another direction, namely, from top right to bottom left. 

![withnc](https://user-images.githubusercontent.com/13161574/57686666-92072c80-766c-11e9-9e82-773527ea7143.png)

![nonc](https://user-images.githubusercontent.com/13161574/57686672-95021d00-766c-11e9-9a4e-9a1669f6a19c.png)

With or without the -nc parameter, the flow directions are almost the same in TauDEM, but very different from what we can see by visual inspection.

Changing different threshold value still doesn't change the flow directions.

Why is it so? And how can I fix this?

Here's the tiff file
[WATERSHED TESTING2.zip](https://github.com/dtarb/TauDEM/files/3176850/WATERSHED.TESTING2.zip)

**Comment by dtarb** [comment]
I think this is the same problem as #193 of the data being flipped due to TauDEM assuming top to bottom ordering.  Until TauDEM is generalized, you may need to reverse the date before using it in TauDEM.

**Comment by WindingWinter** [comment]
![format](https://user-images.githubusercontent.com/13161574/58059367-227acb00-7b9f-11e9-9bb4-0d98e48e71cf.png)


Just right before I call the GDAL engine, I check the geotransform, and  I got the above. Note that geoTransform[5] is -ve, indicating that it is ordered from top to bottom.

I believe that this is not because of #193  issue?

**Comment by dtarb** [comment]
I created a hillshade of your data in ArcGIS and here is what I got
![image](https://user-images.githubusercontent.com/3456833/58067914-82945180-7b4c-11e9-88f8-0e757d536434.png)

This is a vertical flip from the way your data is displayed.

If I then do TauDEM processing I get
![image](https://user-images.githubusercontent.com/3456833/58067944-a3f53d80-7b4c-11e9-9f1c-61e3b00ddb62.png)

The above is contributing area.

Thus ArcGIS is displaying your data consistently.  I think that there is something different in the visualization software that you are using.

**Comment by WindingWinter** [comment]
@dtarb , for the purpose of verification, based on your ArcGIS software,  what is the grid/points that have the maximum z values? In my case, it's occurring near the top right, the toppest point is `{18,176.592, -8,069.349,104.369}`

**Comment by WindingWinter** [comment]
@dtarb , thanks for the pointer, it turns out that the issue is the same as #193 after all-- I didn't handle the reorder correctly in my preprocessing function correctly.

**Comment by dtarb** [comment]
For what it is worth in ArcGIS I get the maximum at
(18176611,  -8999939, 104292)
minimum at
(18338799  -8161249, 736.223)
Horizontal dimensions are about 1000 times yours, perhaps due to cell size being around 1000.  Vertical dimensions I do not know how to reconcile.  The "properties" from ArcGIS are shown as
![image](https://user-images.githubusercontent.com/3456833/58090169-db331100-7b83-11e9-877f-7dde87686301.png)
![image](https://user-images.githubusercontent.com/3456833/58090362-51d00e80-7b84-11e9-89ca-43b322464d74.png)
![image](https://user-images.githubusercontent.com/3456833/58090384-5c8aa380-7b84-11e9-8fad-452a7775fd9e.png)
