### ISSUE TITLE
Error running TauDem in QGIS 2.18.17 on Linux 5.3.0-26-generic

### ISSUE THREAD

**Issue by bhanu-IITD** [dtarb/TauDEM#210]
I have followed this guide [here](https://docs.qgis.org/2.14/en/docs/user_manual/processing/3rdParty.html#installing-taudem-under-linux) to configure TauDem in QGIS 2.18.17 on linux 5.3.0-26-generic. I have also activated the TauDem in processing>options>providers . But , when i run a process (e.g. pitremove) on a test file , it gives me following error : 

> 
Algorithm Pit Remove starting...
TauDEM command:
mpiexec -n 2 /home/bhanu/Applications/TauDEM-Develop/pyfiles/pitremove -z /media/bhanu/Storage/Research/IITD/Projects/EF5/test_dem.tif -fel /home/bhanu/Temp/test_2.tif" 
[proxy:0:0@T-850] HYDU_create_process (utils/launch/launch.c:74): execvp error on file /home/bhanu/Applications/TauDEM-Develop/pyfiles/pitremove (No such file or directory) 
[proxy:0:0@T-850] HYDU_create_process (utils/launch/launch.c:74): execvp error on file /home/bhanu/Applications/TauDEM-Develop/pyfiles/pitremove (No such file or directory) 
Converting outputs
Loading resulting 
layers
> 
Seems like the issue is with the location of TauDEM command line tools folder. I have tried src,pyfiles within the Taudem but they give the same error.
Please help me to resolve this error. 
![image](https://user-images.githubusercontent.com/60338532/73156526-1965d480-4104-11ea-9e05-a5396a8c7c42.png)
![image](https://user-images.githubusercontent.com/60338532/73156540-271b5a00-4104-11ea-9e7e-b509bf40ca9e.png)

**Comment by dtarb** [comment]
I know very little about how QGIS wraps TauDEM.  I suggest you use search tools to locate where TauDEM was installed, or install it again following https://github.com/dtarb/TauDEM/blob/Develop/README.txt and then try run from the command line.  There is a command line guide at http://hydrology.usu.edu/taudem/taudem5/documentation.html.  This is not quite as convenient as running inside QGIS but you should be able to run all commands and show the results in QGIS.

**Comment by bhanu-IITD** [comment]
Thank you ! It worked when I installed it again by following [https://github.com/dtarb/TauDEM/blob/Develop/README.txt ](url) . Now it is working within qgis GUI.
