### ISSUE TITLE
Error 000732 Avalanche Runout

### ISSUE THREAD

**Issue by koreyh** [dtarb/TauDEM#213]
I am receiving Error 000732 while trying to run the 'D-Infinity Avalanche Runout' tool with my own source site data. I have no issues with the 'Pit Remove' or 'Flow Direction' tools to prepare the data. The error claims that the result raster from the Avalanche Runout tool can not be recognized or is not supported. I have checked for spaces in file or folder names, tried projected and unprojected source site raster, tried different location to write to on my machine, and checked the properties of my raster to the example you provide. 

I have also ran the example data from 'Avalanche.zip' that you provide with no issue, so I am assuming that everything is installed correctly. 

Do you have any guidance or recommendations for making your own source site data so that the tool will preform correctly? 

Thank you.

**Comment by dtarb** [comment]
Closing. Inactive
