### ISSUE TITLE
Error in ArcMap / PitRemove.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by micpy** [dtarb/TauDEM#214]
HELP: Error in ArcMap 10.3.1
File "C:\Program Files\TauDEM\TauDEM5Arc\PitRemove.py", line 61, in <module>
    arcpy.CalculateStatistics_management(outFile)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\management.py", line 14618, in CalculateStatistics
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Raster Dataset

Then I tried running it in cmd. This is the error I experienced:
"PitRemove.exe - Entry Point Not Found" [using TauDEM537]
![image](https://user-images.githubusercontent.com/64643054/83198984-e5162980-a172-11ea-8611-7fd5a51006cb.png)
 
Note:
I also experienced the same error with TauDEM535
My unit is 64-bit.
I already added to my Path the following: 
C:\Program Files\Microsoft MPI\Bin\mpiexec.exe;C:\Program Files\Microsoft HPC Pack 2012\Bin\mpiexec.exe;C:\Program Files\GDAL;C:\Program Files\Microsoft HPC Pack 2012;C:\Program Files\TauDEM;C:\Program Files\TauDEM\TauDEM5Exe

**Comment by dtarb** [comment]
I do not immediately know what the problem is, other than what it says about the GDAL library not being found.  Check that you installed the GDAL libraries.  I wonder if somehow you have the 32 bit TauDEM files on a 64 bit GDAL or visa versa.  If you can tell me exact steps from installation to where you receive errors, I may be able to say more.

**Comment by lemker** [comment]
Change your ArcMap shortcut target to reflect proper GDAL paths:

`C:\Windows\System32\cmd.exe /c "SET PATH=C:\Program Files\GDAL;%PATH% && START /D  ^"C:\Program Files (x86)\ArcGIS\Desktop10.8\bin^" ArcMap.exe"`

![image](https://user-images.githubusercontent.com/31901553/94739498-effde800-0325-11eb-85d1-b04b36342eb3.png)

**Comment by dtarb** [comment]
Closing.  Inactive.
