### ISSUE TITLE
Problem in ArcGIS toolbox

### ISSUE THREAD

**Issue by nazmussazib** [dtarb/TauDEM#23]
I have got error/warning message while running "MoveOutletstoStream" and "ConnectDown" function from ArcGIS tool box. However , i have not get any error message while running from command line. After rigorous checking, i have found that those functions create  "data sources" (e.g. any output shapefile), though those functions already have the data sources. I have fixed  and tested those functions both in ArcGIS and command line.

**Comment by dtarb** [comment]
@nazmussazib is this still a concern.  I think this may be superceded by #33.  Please close if this is done and no longer an issue.  Otherwise create a branch and pull request to bring in this fix.

**Comment by dtarb** [comment]
Presumed fixed.  The tool box has had a makeover since this issue.
