### ISSUE TITLE
Outlets in Slope Area Stream Definition not working.

### ISSUE THREAD

**Issue by GitZombieHub** [dtarb/TauDEM#233]
Hi. Long time user of TauDEM here.

Up until recently I've never had any issues with the tool, using it flawlessly on a Windows XP (!!!) with ArcGIS 10.5 for years

But ever since I've upgraded to a Windows 10, I get an error when I run a Slope Area Stream Definition:

> job aborted:
> [ranks] message
> 
> [0] process exited without calling finalize
> 
> ---- error analysis -----
> 
> [0] on DESKTOP-5U1UDP0
> D8FlowPathExtremeUp ended prematurely and may have crashed. exit code 0xc0000005
> 
> ---- error analysis -----
> 
> Failed script SlopeAreaStreamDef...
> 
> Traceback (most recent call last):
>   File "C:\Program Files\TauDEM\TauDEM5Arc\SlopeAreaStreamDefinition.py", line 146, in <module>
>     arcpy.CalculateStatistics_management(ssa)
>   File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\management.py", line 16420, in CalculateStatistics
>     raise e
> ExecuteError: Failed to execute. Parameters are not valid.
> ERROR 000732: Input Raster Dataset: Dataset D:\Freelance\Project PNLC\GeoSpatial\Taudem\srtm_ssa_noedge_t200_out.tif does not exist or is not supported
> Failed to execute (CalculateStatistics).
> 
> 
> Failed to execute (SlopeAreaStreamDef).

The tools works fine if I don't run it with the Outlets shapefile.

Any help on how to fix this would be much appreciated, or at least a direction where I can look for solutions. I guess I can always get back to Windows XP as the last resort.. :)

Thanks in advance and regards from sunny Lagos
Alex

**Comment by dtarb** [comment]
Should not have to return to XP.  I've been using TauDEM with Windows 10 for years.  Keying off your reporting that it works fine without an outlets shapefile, do any of the other functions that use shapefiles work (to verify that OGR part of GDAL library that reads shapefiles is working).  Does the shapefile have needed columns?  Is the Shapefile projection the same, as if not, it may represent a point outside of the domain.  If you run from a command line is the error message any more helpful.  If none of these help you resolve this, send me the data and I can try it out.

**Comment by dtarb** [comment]
Closing as received no response.
