### ISSUE TITLE
updateParameters Execution Error

### ISSUE THREAD

**Issue by Irene816** [dtarb/TauDEM#243]
Hi，dtarb！
I have a tricky question I'd like to ask you.
When I input elevation grid, there comes an error which says,"updateParameters Execution Error: Runtime error Traceback (most recent call last): File "C:\ArcGIS10.2\Tools\pyfiles537\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 4, in File "C:\ArcGIS10.2\Tools\pyfiles537\TauDEM Tools.tbx#PitRemove.UpdateParameters.py", line 28, in updateParameters UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-53: ordinal not in range(128) "
Please tell me the solution,
Thank you!
Irene

**Comment by dtarb** [comment]
Can you please send a screen shot of the input screen before this error occurs.  Taking the error message at face value it looks like an error with some sort of special character, either in the file name of file path of one of the files.  If you can spot a specific special character, try changing the input to avoid this.

**Comment by Irene816** [comment]
I have solved this problem, Thank you!发自我的荣耀手机-------- 原始邮件 --------发件人： David Tarboton ***@***.***>日期： 2022年8月21日周日 08:52收件人： dtarb/TauDEM ***@***.***>抄送： Irene ***@***.***>, Author ***@***.***>主    题： Re: [dtarb/TauDEM] updateParameters Execution Error (Issue #243)
Can you please send a screen shot of the input screen before this error occurs.  Taking the error message at face value it looks like an error with some sort of special character, either in the file name of file path of one of the files.  If you can spot a specific special character, try changing the input to avoid this.

**Comment by Irene816** [comment]
I have a new problem about output grid，the error code is 000732. I will send the screenshot to you later发自我的荣耀手机-------- 原始邮件 --------发件人： David Tarboton ***@***.***>日期： 2022年8月21日周日 08:52收件人： dtarb/TauDEM ***@***.***>抄送： Irene ***@***.***>, Author ***@***.***>主    题： Re: [dtarb/TauDEM] updateParameters Execution Error (Issue #243)
Can you please send a screen shot of the input screen before this error occurs.  Taking the error message at face value it looks like an error with some sort of special character, either in the file name of file path of one of the files.  If you can spot a specific special character, try changing the input to avoid this.

**Comment by dtarb** [comment]
Closing.  Likely special character issue.
