### ISSUE TITLE
 job abortion when run aread8

### ISSUE THREAD

**Issue by xiechou** [dtarb/TauDEM#247]
Dear dtarb!

This TauDEM package is awesome. Thanks for developing it.

TauDEM version: 5.3.7
using command-line tools
operating system: Windows 

After installing TauDEM 5.3.7 on Windows using TauDEM537_setup.exe, I downloaded TestSuite.zip and  unzipped the Logan River example data.

When I tested the example data using command-line tools,   the functions, such as removing pits, flow directions, went through  smoothly.

 I met job abortion when run aread8 as following:
mpiexec -n 8 Aread8 -p loganp.tif -o loganoutlet.shp -ad8 loganad8o.tif

I attached  some screenshots of the the varying outputs here.

###############################
job aborted.
[ranks]  message

[0] application aborted
aborting MPI_COMM_WORLD (comm=ox44000000), error 5, comm rank 0

[1-7] terminated

------ error analysis  ---------------------

[0]  on xiechou-HP
Aread8 aborted the job. abort code 5

------ error analysis  ---------------------

###########################################

Thanks for your attention!

**Comment by xiechou** [comment]
I found the solution. I should copy loganoutlet.shp to the same folder, and then implement the command line 
mpiexec -n 8 Aread8 -p loganp.tif -o loganoutlet.shp -ad8 loganad8o.tif

Everything seems ok now.

**Comment by dtarb** [comment]
I am glad it is working now.
