### ISSUE TITLE
I have encountered a problem and I need urgent assistance. Thank you very much for your help.

### ISSUE THREAD

**Issue by zhanglu-666** [dtarb/TauDEM#262]
Hello, when I was executing the command in the command line, I encountered an issue during the final step of converting a TIFF file to a shapefile. I executed the following command: `mpiexec -n 8 WaterShedGridToShapefile loganw.tif loganw.shp`. However, it was not successful, and it gave an error stating that the file could not be found. I tried looking for the executable file for this command in the folder "C:\Program Files\TauDEM\TauDEM5Exe", but I couldn't find it. Can you please help me resolve this issue? Thank you very much.
![微信图片_20231213205436](https://github.com/dtarb/TauDEM/assets/103102718/61b289be-3dce-4422-9713-cd1682fcef4d)

**Comment by dtarb** [comment]
There is no watershedgridtoshapefile command line executable.  Here TauDEM uses a built in ArcGIS function to produce a shapefile from the grid.  If you see https://hydrology.usu.edu/taudem/taudem5/help53/WatershedGridToShapefile.html it does not list the mpiexec command as an option, while for other functions (e.g https://hydrology.usu.edu/taudem/taudem5/help53/StreamReachAndWatershed.html) it does.

**Comment by zhanglu-666** [comment]
I understand now. Thank you very much for your response and for your explanation.
