### ISSUE TITLE
Raster statistics appear to be copied and not updated

### ISSUE THREAD

**Issue by mwtoews** [dtarb/TauDEM#3]
When running commands like `DinfFlowDir`, the raster statistics embedded in GeoTIFF files from the input files appear in the output files. E.g. The input stats from the source DEM are shown with `gdalinfo input.tif`:
```
Driver: GTiff/GeoTIFF
Files: input.tif
Size is 2200, 3200
...
Band 1 Block=2200x128 Type=Float32, ColorInterp=Gray
  Min=144.480 Max=1108.735
  Minimum=144.480, Maximum=1108.735, Mean=466.574, StdDev=133.894
  NoData Value=-3.0000000054977558e+038
  Metadata:
    STATISTICS_MAXIMUM=1108.7349853516
    STATISTICS_MEAN=466.57443054098
    STATISTICS_MINIMUM=144.47999572754
    STATISTICS_STDDEV=133.89387030864
```
Within the binary GeoTIFF file, the metadata is stored at tag 42112 (see [`TIFFTAG_GDAL_METADATA`](https://github.com/OSGeo/gdal/blob/trunk/gdal/frmts/gtiff/gtiff.h#L49))
```
<GDALMetadata>
  <Item name="STATISTICS_MAXIMUM" sample="0">1108.7349853516</Item>
  <Item name="STATISTICS_MEAN" sample="0">466.57443054098</Item>
  <Item name="STATISTICS_MINIMUM" sample="0">144.47999572754</Item>
  <Item name="STATISTICS_STDDEV" sample="0">133.89387030864</Item>
</GDALMetadata>
```

The problem is that the identical statistics are also in the output files too, for example the flow direction raster, which is misleading to tools that read the rasters. For example, ArcToolbox shows the flow direction raster as all black, since the values in the raster are are irrelevant for the statistics from another raster.

I'm not sure what's going on exactly in TauDEM, except that looks like this metadata is copied. I see tag 42112 in, for example, [src/tifFile.cpp#L371](https://github.com/dtarb/TauDEM/blob/master/src/tifFile.cpp#L371), but I'm not sure how it is used.

The fix is to either update the metadata items with the correct statistics for the output rasters, or don't copy the lines from tag 42112 that match "STATISTICS_*" (the later strategy is done by `gdalwarp` [as show in the source code](https://github.com/OSGeo/gdal/blob/trunk/gdal/apps/gdalwarp.cpp#L1055)). The statistics can be recalculated afterwards using `gdalinfo -stats output.tif`.

**Comment by dtarb** [comment]
This is true and is an issue.  A short term fix would be to fiddle in the tiffio library, but I am loath to do that as tiffio has significant limitations and is at a dead end.  A longer term fix that we are working on is to replace the use of tiffio library with the GDAL library.  Then hopefully this and other I/O issues will be resolved.  I am hoping that we can get to this in the next few months.  Until then the workaround of computing statistics afterwards will have to suffice, unless there is someone who can get to the implementation of GDAL as an IO library before us.

**Comment by mwtoews** [comment]
Great to hear plans to use GDAL; [GDALRasterBand::ComputeStatistics](http://www.gdal.org/classGDALRasterBand.html#a48883c1dae195b21b37b51b10e910f9b) is the function to do this.

**Comment by dtarb** [comment]
@nazmussazib please check if the GDAL implementation resolves this.  Please evaluate whether GDALRasterBand::ComputeStatistics should be performed on each raster output by TauDEM and implement if necessary.  The current strategy is

1. Python script is called by ArcGIS toolbox tools.
2. Python script calls TauDEM C++ command line function.
3. Python script runs compute statistics on result.

The limitation of this is that statistics are only evaluated automatically in the ArcGIS implementation.

Including ComputeStatistics in the C++ command line functions would make statistics available to all deployments, not only ArcGIS, however there may be a computational hit, and the parallel large grid performance is unknown and needs to be evaluated.

**Comment by dtarb** [comment]
Closing.  GDAL implementation will have resolved the incorrect statistics from tiffio.  Our C++ code does not comute statistics.  It is unclear whether GDAL does this internally, but even if not I am loathe to fiddle without a pressing concern.  There is always the option to run a separate GDAL function to compute statistics, and one could argue this is better anyway as not all codes need to be burdened by statistics evaluation.

**Comment by mwtoews** [comment]
GDAL does not automatically calculate statistics, and I think it's best to leave that to the users to figure out.
