### ISSUE TITLE
ORDINAL NOT FOUND Error (PitRemove.exe)

### ISSUE THREAD

**Issue by hermesys** [dtarb/TauDEM#45]
Thank you for a good software you provide. 
I have a question while using it.
TauDEM works without problems like installing and operating on most computers.
On some computers, however, when I execute PitRemove.exe in CMD.EXE, 
the error appears like “ORDINAL NOT FOUND. THE ORDINAL [xxxx] COULD NOT BE LOCATED IN THE DYNAMIC LINK LIBRARY LIBEAY32.DLL”.
 
The path of OS is like this:
Path= C:\Program Files\Microsoft HPC Pack 2012\Bin\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\GDAL;C:\Program Files\GDAL;C:\Program Files\TauDEM\TauDEM5Exe
 
When I execute “Copy C:\Program Files\GDAL\*.DLL C:\Program Files\TauDEM\TauDEM5Exe\ ” in CMD.EXE, this PitRemove.exe error disappears. 
Could you let me know why this error occur on some computer?
 
Best Regards,
YJ Won

**Comment by dtarb** [comment]
Try "where gdal_translate" at a command prompt.  This should show the path (or multiple paths) to where GDAL functions are on your system.  It may indicate a problem with how path information is set during the install that we need to check on.  Is there a pattern to the problem, like perhaps it only occurs on 32 bit computers.

**Comment by dtarb** [comment]
@pkdash can you please give your thoughts on this and see if there may be a path issue in the installer.  @hermesys can you please confirm which version of taudem you are using.

**Comment by hermesys** [comment]
Thank you for your quick reply.
I’m using TauDEM version 5.3.1 and the error like “[ORDINAL NOT FOUND Error (PitRemove.exe)” appears only in Win7 32bit OS. 
I’m trying to find out the meaningful pattern and I’m going to use the method “where gdal_translate” given you.
Thank you.
YJ Won

**Comment by pkdash** [comment]
I will be doing some testing on this.

**Comment by dtarb** [comment]
Closing as traffic has dwindled.  Feel free to open if this is still an issue.
