### ISSUE TITLE
TauDEM logo in vector format

### ISSUE THREAD

**Issue by alexbruy** [dtarb/TauDEM#56]
It would be good to have TauDEM logo in vector format, e.g. SVG to use in documentation and applications which calls TauDEM tools.

**Comment by mach0** [comment]
I took the freedom and created one with the current existing one as blueprint.
Feel free to take it, change it and make it better ;)

It was made with inkscape - so it should also open with inkscape without problems.

[taudem.zip](https://github.com/dtarb/TauDEM/files/197442/taudem.zip)

**Comment by dtarb** [comment]
Cool! Thanks.  I'll add this to the code base (in WindowsInstaller folder).
