### ISSUE TITLE
Switch to GDAL

### ISSUE THREAD

**Issue by alexbruy** [dtarb/TauDEM#6]
It would be great to use GDAL in TauDEM to read/write both rasters and vectors. This allow to support not only TIFF rasters but also many other formats. Also with GDAL we can get rid of two versions: single- and multi-file, as GDAL provides so-called "virtual" rasters, which wrap multiple files into single one.

**Comment by dtarb** [comment]
The code for this is committed and once testing is complete a new version will be deployed (no later than end October 2015).
