### ISSUE TITLE
Compilation problem in Debian

### ISSUE THREAD

**Issue by privatemajory** [dtarb/TauDEM#67]
Hi.

I get this when running make in Debian 8.4, please let me know how to fix this if there's a way:

>mpic++ -g  -c areadinfmn.cpp -o areadinfmn.o
>In file included from areadinfmn.cpp:46:0:
>commonLib.h:46:21: fatal error: ogr_api.h: Aucun fichier ou dossier de ce type
> #include "ogr_api.h"
>                     ^
>compilation terminated.
>makefile:179: recipe for target 'areadinfmn.o' failed
>make: *** [areadinfmn.o] Error 1

Thank you.

**Comment by dtarb** [comment]
I am not familiar with Debian specifics.  In general, you will need to make sure that the GDAL/OGR software is installed and that your include path references this file.  In my installation (on a PC) the file is in C:\GDAL\include.  Perhaps @ahmetartu or @nazmussazib can comment on how to set up Linux include paths to GDAL and if the makefile needs changing.

**Comment by ahmetartu** [comment]
Hi,

I will talk about 2 ways to compile TauDEM on Linux systems. 

1. Compiling the source files one by one as you showed using mpic++. In this case, you should show the mpi compiler where to find the gdal library and include files. After installing gdal-dev package using apt-get in debian-based distros, run "sudo updatedb" and then "locate gdal.h" to find the header file's location. For example, gdal.h file is located at "/usr/include/gdal/gdal.h" in my ubuntu machine. Then you should use such a command below to compile:

mpic++ -g -c -I/usr/include/gdal -lgdal areadinfmn.cpp -o areadinfmn.o

Note that here -I option specifies include directory of header files. mpic++ is basically using gcc options, thus please refer to gcc manuals for more information. You must also specify gdal library for the linker via -lgdal option. 

2. Second option is to use make that streamlines those process for you, or something like cmake that I highly recommend. We have a cmake script file that you don't need to specify where gdal include and library files are located. cmake automatically finds dependent libraries header and library locations for you and nicely compiles the TauDEM. So first, please install cmake into your system. "sudo apt-get install cmake". I put the new CMakeLists.txt file of TauDEM in this comment (the existing one is outdated please use that version), copy/overwrite the file into src directory of TauDEM project. Then just type "cmake" in terminal in src directory. It will compile all of the TauDEM programs for you. Later, we will update cmake file with the new version of TauDEM.

[CMakeLists.txt](https://github.com/dtarb/TauDEM/files/249526/CMakeLists.txt)

**Comment by dtarb** [comment]
Thanks @ahmetartu.  I updated the develop branch with this CmakeLists.txt file.

**Comment by privatemajory** [comment]
Thank you. The compiltation worked after uncommenting some line in the make file as described in the **README.md** file. But how do I install it in my system now? Running `sudo make install` gives `make: *** No rule to make target 'package'.Stop.` and there seems no install script generated anywhere. Sorry I'm not good at compiling but I need TauDEM on my PC so please can you show me the steps?

**Comment by privatemajory** [comment]
Sorry for disturbing but it finally did with `CXX=mpicxx cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..`. I think you should just provide some guidance for compilation and installation on linux. Many thanks!

**Comment by privatemajory** [comment]
Only **gagewatershed** isn't included :disappointed:

**Comment by dtarb** [comment]
@ahmetartu can you please add gagewatershed to the cmake file.  It is one of the newer functions added in Visual Studio in Windows, but the linux makefiles have not kept up.

**Comment by ahmetartu** [comment]
I added cmake directions to CMakeFiles.txt to compile gagewatershed. It is compiling OK in my ubuntu machine.

I listed the following steps to clarify the installation through CMake 

[1] It is mostly recommended way to create a temporary directory and run cmake within that not to make the source directory dirty with the intermediate compilation files. So as you see below, I created a directory named "bin" in the TauDEM folder

```
cd TauDEM
mkdir bin
```

[2] Then run the cmake tool in the bin (temp. folder). You must locate the CMakeLists.txt file for the cmake tool to find it, which is located at Taudem/src folder

```
cd bin
cmake ../src/
```

In most linux systems, particularly new ones, cmake should detect all the dependencies well, but please note that in some linux systems (like supercomputers or old systems), cmake might fail in finding gdal header files. Then you should explicitly show the GDAL include library to cmake (in my case, gdal.h is at /usr/gdal/include). In such cases, the cmake command should look like this:

`cmake ../src/ -DGDAL_INCLUDE_DIR=/usr/gdal/include`

[3] cmake tool should find the MPI and gdal libraries and generate a Makefile which is used to compile source files into executables. Then we basically run make command for that.

`make`

**Comment by privatemajory** [comment]
Thank you.
