### ISSUE TITLE
Correct "int" type in D8 for large DEM

### ISSUE THREAD

**Issue by fbourgin** [dtarb/TauDEM#68]
Hi,

I had issues with the application of the D8FlowDir function for a large DEM (more than 7 GB).
It seems that some flat areas are not resolved when located in a column larger than 32,767.
In fact, the "short" type is used for two variables in the function setFlow2 of the file d8.cpp.
Changing the type of the two variables "in" and "jn" to "int" solved my issues.

**Comment by dtarb** [comment]
Thanks for letting us know.  We'll make this change in a future release.

**Comment by dtarb** [comment]
The code base has been changed to include this fix (#69) so this will be part of whatever is the next release.
