### ISSUE TITLE
Visual Studio: Updated Microsoft MPI SDK Install locations

### ISSUE THREAD

**Issue by sina-masoud-ansari** [dtarb/TauDEM#7]
Microsoft has updated its installation locations for the MPI SDK.

Suggest using $(MPI)\Include and $(MPI)\Lib to replace instances of 'C:\Program Files\Microsoft HPC Pack 2012\Inc' and 'C:\Program Files\Microsoft HPC Pack 2012\Lib\amd64'

Users can set their install locations via the MPI environment variable. 

If you agree, I can create a pull request.

Cheers

**Comment by sina-masoud-ansari** [comment]
Created a pull request so we can discuss there if you like.

**Comment by dtarb** [comment]
Thanks.  I'll take a look.
