### ISSUE TITLE
Flow direction conditioning

### ISSUE THREAD

**Issue by dtarb** [dtarb/TauDEM#70]
Develop a new TauDEM “Flow direction conditioning” tool that soft burns in elevations by tracking down D8 flow directions to ensure there is no uphill elevation.  This to be part of procedure for etching vector stream network into DEM for inundation mapping.  This is step 6 in the following overall procedure.
1.  Inputs are a stream vector file (e.g. NHD or NHD High Res) and a DEM (denoted z).
2.  Convert the stream vectors to raster that shares the same dimensions (columns, rows, cell size and edge coordinates as the DEM), denoted srfv (stream raster from vector) with values 1 on stream and 0 off stream
3.  Burn srfv into z using raster calculator  zb = z-100 \* srfv  (or any big number in place of 100)
4.  D8FlowDir with input zb and output flow directions p
5.  Mask D8 flow directions to only have flow directions on streams.  The raster calculation pm = p/srvf achieves this
6.  Develop a new TauDEM “Flow direction conditioning” tool that operates on pm and z and produces zsb (soft burned elevations) by tracking down the D8 flow directions and ensuring there is no uphill elevation.

**Comment by jasmingillfortin** [comment]
Hi,

I am trying to use this function with the latest version of TAUDEM without success. Do you have an idea of ​​where the problem might come from? 

Command Line : 
mpiexec -n 8 flowdircond -p PM.tif -z DEM.tif 

Error : 
process exited without calling finalize
flowdircond ended prematurely and may have crashed. exit code 0xc0000005

Thank you

**Comment by dtarb** [comment]
Try
mpiexec -n 8 flowdircond -p PM.tif -z DEM.tif -zfdc demconditioned.tif

You need to give a file name for the results to be written to.  I should have better error trapping for a file not given.

**Comment by jasmingillfortin** [comment]
Thank you for the answer. I should have mentioned it, but I also tried with the result without success (same error)

**Comment by dtarb** [comment]
Some things to check/try
- Do PM.tif and DEM.tif have same number of rows and columns.  Inputs are supposed to be checked for this, but this may have been forgotten for this implementation.
- Is there a value in PM.tif that is an invalid flow direction, i.e. not no data or a number between 1 and 8.  Again - robust coding would check this, but I am not sure.
- Flow directions that do not go in a loop.  I am not sure if the recursive checking checks for this.
- Does the DEM size (rows x columns) result in a memory overflow
- Try with a different number of processes, e.g. 1, to rule out message passing issues
- Try run in a step by step debugger to see where the error occurs
- If all the above fail, and you are able to send me the data (and it is not huge), I can try in a step by step debugger to see if I can find out what is going on.

**Comment by vcantarella** [comment]
> I finally solved my problem by changing PM.tif from 16bit signed to 16bit unsigned.. Thank you

Thanks for leaving the feedback. This worked for me.
