### ISSUE TITLE
Can't run PitRemove

### ISSUE THREAD

**Issue by gena** [dtarb/TauDEM#9]
Are the latest sources actually broken? 

I've tried to compile everything, but getting errors in tiffIO constructor. It is called using filename but tiffIO constructor actually expects directory:

flood.cpp:73
   ...
   tiffIO dem(demfile,FLOAT_TYPE); 
   ...

tiffIO:61
   ... 
   tiffIO::tiffIO(char *dirname, DATA_TYPE newtype){
   ...

**Comment by dtarb** [comment]
This version of TauDEM (the multifile version) is supposed to take a directory as input.  The logic is that all the tiff files in the directory comprise a single logical grid.  This was done to overcome the 4GB limitation of TIFF files.  If you put your input file in a directory by itself and run the programs the should work.  See http://hydrology.usu.edu/taudem/taudem5/TauDEM52CommandLineGuideMF.pdf.

**Comment by gena** [comment]
Thanks, will try as a directory.
