### ISSUE TITLE
OGR write errors from streamnet on ubuntu

### ISSUE THREAD

**Issue by dtarb** [dtarb/TauDEM#93]
A user had the following error 

mpiexec -n 8 streamnet -fel loganfel.tif -p loganp.tif -ad8 loganad8.tif -src logansrc.tif -ord loganord.tif -tree logantree.txt -coord logancoord.txt -net logannet.shp -w loganw.tif -o LoganOutlet.shp

StreamNet version 5.3.5
Input file logansrc.tif has projected coordinate system.
This run may take on the order of 3 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file loganp.tif has projected coordinate system.
Input file loganad8.tif has projected coordinate system.
Input file loganfel.tif has projected coordinate system.
Warning: Spatial Reference of Outlet feature is missing.
Projection of Raster datasource NAD83 / UTM zone 12N.
Evaluating distances to outlet
Creating links
logannet ERROR 10: Name was NULL in OGR_DS_CreateLayer
warning: Layer creation failed.
ERROR 10: Pointer 'hLayer' is NULL in 'OGR_L_CreateField'.

ERROR 10: Pointer 'hLayer' is NULL in 'OGR_L_CreateField'.
...

**Comment by snowman2** [comment]
I have the same issue. Here is the path to the DEM I used: https://github.com/erdc-cm/RAPIDpy/blob/master/tests/data/gis/jamaica_dem.tif. 

I ran into it when creating tests for the RAPIDpy code.
The code I ran is on line 481 of https://github.com/erdc-cm/RAPIDpy/blob/master/tests/test_gis.py

**Comment by dtarb** [comment]
A user wrote

> I ran into the streamnet issue reported in https://github.com/dtarb/TauDEM/issues/93.
>
> I looked at the code and tried a few things.  I eventually decided that the function getLayername in commonLib is trying to return a pointer to an array declared in the function.  I guess that since this is a variable local to the function, the array is being reclaimed and the pointer set to null on exit.  At any rate, null is what is returned. 
> Maybe this is a recent change to the C++ compiler.
> 
> I have changed getLayername so that it takes a char array as its second argument, into which the result is placed.  I don't know if this is the best solution - I am very far from being a C++ expert - but it seems to work.  There are 4 files which use getLayername, which I have updated. 
> All the affected files are attached.
> 
> You should run this through whatever tests you have - I have done nothing more so far than get streamnet to run on one example.

I responded that I really appreciate this suggestion but do not have time to look at this right now.  The files he attached are here.
[FilesFromChris.zip](https://github.com/dtarb/TauDEM/files/1425540/FilesFromChris.zip)

**Comment by dtarb** [comment]
The changes from Chris were added to the code base, all tests verified, and will be part of next release.
